// This File was auto generated by BungoKitGen
//
// File: DestinyColor.swift

import Foundation

public extension Destiny.Misc {
    /// Represents a color whose RGBA values are all represented as values between 0 and 255.
    struct DestinyColor: Codable {
        public var alpha: UInt8?
        public var blue: UInt8?
        public var green: UInt8?
        public var red: UInt8?

        public enum CodingKeys: String, CodingKey {
            case alpha
            case blue
            case green
            case red
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            alpha = try? container.decode(UInt8.self, forKey: CodingKeys.alpha)
            blue = try? container.decode(UInt8.self, forKey: CodingKeys.blue)
            green = try? container.decode(UInt8.self, forKey: CodingKeys.green)
            red = try? container.decode(UInt8.self, forKey: CodingKeys.red)
        }
    }
}
