// This File was auto generated by BungoKitGen
//
// File: DestinyItemSocketsComponent.swift

import Foundation

public extension Destiny.Entities.Items {
    /// Instanced items can have sockets, which are slots on the item where plugs can be inserted.
    /// Sockets are a bit complex: be sure to examine the documentation on the DestinyInventoryItemDefinition's "socket" block and elsewhere on these objects for more details.
    struct DestinyItemSocketsComponent: Codable {
        /// The list of all sockets on the item, and their status information.
        public var sockets: [Destiny.Entities.Items.DestinyItemSocketState]?

        public enum CodingKeys: String, CodingKey {
            case sockets
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            sockets = try? container.decode([Destiny.Entities.Items.DestinyItemSocketState].self, forKey: CodingKeys.sockets)
        }
    }
}
