// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetCommonSettings.swift

import Foundation

public extension Requests {
    /// Get the common settings used by the Bungie.Net environment.
    struct GetCommonSettingsRequest: BungoRequest {
        public typealias Response = Common.Models.CoreSettingsConfiguration

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Settings/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init() {
            parameters = .init()
        }
    }
}
