// This File was auto generated by BungoKitGen
//
// File: DestinyMilestoneChallengeActivityPhase.swift

import Foundation

public extension Destiny.Definitions.Milestones {
    struct DestinyMilestoneChallengeActivityPhase: Codable {
        /// The hash identifier of the activity's phase.
        public var phaseHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case phaseHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            phaseHash = try? container.decode(UInt32.self, forKey: CodingKeys.phaseHash)
        }
    }
}
