// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyCollectibleNodeDetailResponse.swift

import Foundation

public extension Destiny.Responses {
    /// Returns the detailed information about a Collectible Presentation Node and any Collectibles that are direct descendants.
    struct DestinyCollectibleNodeDetailResponse: Codable {
        /// Item components, keyed by the item hash of the items pointed at collectibles found under the requested Presentation Node.
        /// NOTE: I had a lot of hemming and hawing about whether these should be keyed by collectible hash or item hash... but ultimately having it be keyed by item hash meant that UI that already uses DestinyItemComponentSet data wouldn't have to have a special override to do the collectible -> item lookup once you delve into an item's details, and it also meant that you didn't have to remember that the Hash being used as the key for plugSets was different from the Hash being used for the other Dictionaries. As a result, using the Item Hash felt like the least crappy solution.
        /// We may all come to regret this decision. We will see.
        /// COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
        public var collectibleItemComponents: DestinyItemComponentSetOfuint32?

        /// COMPONENT TYPE: Collectibles
        public var collectibles: SingleComponentResponse<Destiny.Components.Collectibles.DestinyCollectiblesComponent>?

        public enum CodingKeys: String, CodingKey {
            case collectibleItemComponents
            case collectibles
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            collectibleItemComponents = try? container.decode(DestinyItemComponentSetOfuint32.self, forKey: CodingKeys.collectibleItemComponents)
            collectibles = try? container.decode(SingleComponentResponse<Destiny.Components.Collectibles.DestinyCollectiblesComponent>.self, forKey: CodingKeys.collectibles)
        }
    }
}
