// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyProfileResponse.swift

import Foundation

public extension Destiny.Responses {
    /// The response for GetDestinyProfile, with components for character and item-level data.
    struct DestinyProfileResponse: Codable {
        /// Character activity data - the activities available to this character and its status, keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterActivities
        public var characterActivities: DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterActivitiesComponent>?

        /// COMPONENT TYPE: Collectibles
        public var characterCollectibles: DictionaryComponentResponse<Int64, Destiny.Components.Collectibles.DestinyCollectiblesComponent>?

        /// COMPONENT TYPE: Craftables
        public var characterCraftables: DictionaryComponentResponse<Int64, Destiny.Components.Craftables.DestinyCraftablesComponent>?

        /// A "lookup" convenience component that can be used to quickly check if the character has access to items that can be used for purchasing.
        /// COMPONENT TYPE: CurrencyLookups
        public var characterCurrencyLookups: DictionaryComponentResponse<Int64, Destiny.Components.Inventory.DestinyCurrenciesComponent>?

        /// The character's equipped items, keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterEquipment
        public var characterEquipment: DictionaryComponentResponse<Int64, Destiny.Entities.Inventory.DestinyInventoryComponent>?

        /// The character-level non-equipped inventory items, keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterInventories
        public var characterInventories: DictionaryComponentResponse<Int64, Destiny.Entities.Inventory.DestinyInventoryComponent>?

        /// Items available from Kiosks that are available to a specific character as opposed to the account as a whole. It must be combined with data from the profileKiosks property to get a full picture of the character's available items to check out of a kiosk.
        /// This component returns information about what Kiosk items are available to you on a *Character* level. Usually, kiosk items will be earned for the entire Profile (all characters) at once. To find those, look in the profileKiosks property.
        /// COMPONENT TYPE: Kiosks
        public var characterKiosks: DictionaryComponentResponse<Int64, Destiny.Components.Kiosks.DestinyKiosksComponent>?

        /// The character loadouts, keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterLoadouts
        public var characterLoadouts: DictionaryComponentResponse<Int64, Destiny.Components.Loadouts.DestinyLoadoutsComponent>?

        /// When sockets refer to reusable Plug Sets (see DestinyPlugSetDefinition for more info), this is the set of plugs and their states, per character, that are character-scoped.
        /// This comes back with ItemSockets, as it is needed for a complete picture of the sockets on requested items.
        /// COMPONENT TYPE: ItemSockets
        public var characterPlugSets: DictionaryComponentResponse<Int64, Destiny.Components.PlugSets.DestinyPlugSetsComponent>?

        /// COMPONENT TYPE: PresentationNodes
        public var characterPresentationNodes: DictionaryComponentResponse<Int64, Destiny.Components.Presentation.DestinyPresentationNodesComponent>?

        /// Character-level progression data, keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterProgressions
        public var characterProgressions: DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterProgressionComponent>?

        /// COMPONENT TYPE: Records
        public var characterRecords: DictionaryComponentResponse<Int64, Destiny.Components.Records.DestinyCharacterRecordsComponent>?

        /// Character rendering data - a minimal set of info needed to render a character in 3D - keyed by the Character's Id.
        /// COMPONENT TYPE: CharacterRenderData
        public var characterRenderData: DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterRenderComponent>?

        /// COMPONENT TYPE: StringVariables
        public var characterStringVariables: DictionaryComponentResponse<Int64, Destiny.Components.StringVariables.DestinyStringVariablesComponent>?

        /// Do you ever get the feeling that a system was designed *too* flexibly? That it can be used in so many different ways that you end up being unable to provide an easy to use abstraction for the mess that's happening under the surface?
        /// Let's talk about character-specific data that might be related to items without instances. These two statements are totally unrelated, I promise.
        /// At some point during D2, it was decided that items - such as Bounties - could be given to characters and *not* have instance data, but that *could* display and even use relevant state information on your account and character.
        /// Up to now, any item that had meaningful dependencies on character or account state had to be instanced, and thus "itemComponents" was all that you needed: it was keyed by item's instance IDs and provided the stateful information you needed inside.
        /// Unfortunately, we don't live in such a magical world anymore. This is information held on a per-character basis about non-instanced items that the characters have in their inventory - or that reference character-specific state information even if it's in Account-level inventory - and the values related to that item's state in relation to the given character.
        /// To give a concrete example, look at a Moments of Triumph bounty. They exist in a character's inventory, and show/care about a character's progression toward completing the bounty. But the bounty itself is a non-instanced item, like a mod or a currency. This returns that data for the characters who have the bounty in their inventory.
        /// I'm not crying, you're crying Okay we're both crying but it's going to be okay I promise Actually I shouldn't promise that, I don't know if it's going to be okay
        public var characterUninstancedItemComponents: [Int: DestinyBaseItemComponentSetOfuint32]?

        /// Basic information about each character, keyed by the CharacterId.
        /// COMPONENT TYPE: Characters
        public var characters: DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterComponent>?

        /// Information about instanced items across all returned characters, keyed by the item's instance ID.
        /// COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
        public var itemComponents: DestinyItemComponentSetOfint64?

        /// COMPONENT TYPE: Metrics
        public var metrics: SingleComponentResponse<Destiny.Components.Metrics.DestinyMetricsComponent>?

        /// Silver quantities for any platform on which this Profile plays destiny.
        ///  COMPONENT TYPE: PlatformSilver
        public var platformSilver: SingleComponentResponse<Destiny.Components.Inventory.DestinyPlatformSilverComponent>?

        /// The basic information about the Destiny Profile (formerly "Account").
        /// COMPONENT TYPE: Profiles
        public var profile: SingleComponentResponse<Destiny.Entities.Profiles.DestinyProfileComponent>?

        /// COMPONENT TYPE: Collectibles
        public var profileCollectibles: SingleComponentResponse<Destiny.Components.Collectibles.DestinyProfileCollectiblesComponent>?

        /// COMPONENT TYPE: SocialCommendations
        public var profileCommendations: SingleComponentResponse<Destiny.Components.Social.DestinySocialCommendationsComponent>?

        /// The profile-level currencies owned by the Destiny Profile.
        /// COMPONENT TYPE: ProfileCurrencies
        public var profileCurrencies: SingleComponentResponse<Destiny.Entities.Inventory.DestinyInventoryComponent>?

        /// The profile-level inventory of the Destiny Profile.
        /// COMPONENT TYPE: ProfileInventories
        public var profileInventory: SingleComponentResponse<Destiny.Entities.Inventory.DestinyInventoryComponent>?

        /// Items available from Kiosks that are available Profile-wide (i.e. across all characters)
        /// This component returns information about what Kiosk items are available to you on a *Profile* level. It is theoretically possible for Kiosks to have items gated by specific Character as well. If you ever have those, you will find them on the characterKiosks property.
        /// COMPONENT TYPE: Kiosks
        public var profileKiosks: SingleComponentResponse<Destiny.Components.Kiosks.DestinyKiosksComponent>?

        /// When sockets refer to reusable Plug Sets (see DestinyPlugSetDefinition for more info), this is the set of plugs and their states that are profile-scoped.
        /// This comes back with ItemSockets, as it is needed for a complete picture of the sockets on requested items.
        /// COMPONENT TYPE: ItemSockets
        public var profilePlugSets: SingleComponentResponse<Destiny.Components.PlugSets.DestinyPlugSetsComponent>?

        /// COMPONENT TYPE: PresentationNodes
        public var profilePresentationNodes: SingleComponentResponse<Destiny.Components.Presentation.DestinyPresentationNodesComponent>?

        /// When we have progression information - such as Checklists - that may apply profile-wide, it will be returned here rather than in the per-character progression data.
        /// COMPONENT TYPE: ProfileProgression
        public var profileProgression: SingleComponentResponse<Destiny.Components.Profiles.DestinyProfileProgressionComponent>?

        /// COMPONENT TYPE: Records
        public var profileRecords: SingleComponentResponse<Destiny.Components.Records.DestinyProfileRecordsComponent>?

        /// COMPONENT TYPE: StringVariables
        public var profileStringVariables: SingleComponentResponse<Destiny.Components.StringVariables.DestinyStringVariablesComponent>?

        /// COMPONENT TYPE: Transitory
        public var profileTransitoryData: SingleComponentResponse<Destiny.Components.Profiles.DestinyProfileTransitoryComponent>?

        /// Records the timestamp of when most components were last generated from the world server source. Unless the component type is specified in the documentation for secondaryComponentsMintedTimestamp, this value is sufficient to do data freshness.
        public var responseMintedTimestamp: Date?

        /// Some secondary components are not tracked in the primary response timestamp and have their timestamp tracked here. If your component is any of the following, this field is where you will find your timestamp value:
        ///  PresentationNodes, Records, Collectibles, Metrics, StringVariables, Craftables, Transitory
        ///  All other component types may use the primary timestamp property.
        public var secondaryComponentsMintedTimestamp: Date?

        /// Recent, refundable purchases you have made from vendors. When will you use it? Couldn't say...
        /// COMPONENT TYPE: VendorReceipts
        public var vendorReceipts: SingleComponentResponse<Destiny.Entities.Profiles.DestinyVendorReceiptsComponent>?

        public enum CodingKeys: String, CodingKey {
            case characterActivities
            case characterCollectibles
            case characterCraftables
            case characterCurrencyLookups
            case characterEquipment
            case characterInventories
            case characterKiosks
            case characterLoadouts
            case characterPlugSets
            case characterPresentationNodes
            case characterProgressions
            case characterRecords
            case characterRenderData
            case characterStringVariables
            case characterUninstancedItemComponents
            case characters
            case itemComponents
            case metrics
            case platformSilver
            case profile
            case profileCollectibles
            case profileCommendations
            case profileCurrencies
            case profileInventory
            case profileKiosks
            case profilePlugSets
            case profilePresentationNodes
            case profileProgression
            case profileRecords
            case profileStringVariables
            case profileTransitoryData
            case responseMintedTimestamp
            case secondaryComponentsMintedTimestamp
            case vendorReceipts
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            characterActivities = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterActivitiesComponent>.self, forKey: CodingKeys.characterActivities)
            characterCollectibles = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Collectibles.DestinyCollectiblesComponent>.self, forKey: CodingKeys.characterCollectibles)
            characterCraftables = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Craftables.DestinyCraftablesComponent>.self, forKey: CodingKeys.characterCraftables)
            characterCurrencyLookups = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Inventory.DestinyCurrenciesComponent>.self, forKey: CodingKeys.characterCurrencyLookups)
            characterEquipment = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Inventory.DestinyInventoryComponent>.self, forKey: CodingKeys.characterEquipment)
            characterInventories = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Inventory.DestinyInventoryComponent>.self, forKey: CodingKeys.characterInventories)
            characterKiosks = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Kiosks.DestinyKiosksComponent>.self, forKey: CodingKeys.characterKiosks)
            characterLoadouts = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Loadouts.DestinyLoadoutsComponent>.self, forKey: CodingKeys.characterLoadouts)
            characterPlugSets = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.PlugSets.DestinyPlugSetsComponent>.self, forKey: CodingKeys.characterPlugSets)
            characterPresentationNodes = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Presentation.DestinyPresentationNodesComponent>.self, forKey: CodingKeys.characterPresentationNodes)
            characterProgressions = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterProgressionComponent>.self, forKey: CodingKeys.characterProgressions)
            characterRecords = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.Records.DestinyCharacterRecordsComponent>.self, forKey: CodingKeys.characterRecords)
            characterRenderData = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterRenderComponent>.self, forKey: CodingKeys.characterRenderData)
            characterStringVariables = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Components.StringVariables.DestinyStringVariablesComponent>.self, forKey: CodingKeys.characterStringVariables)
            characterUninstancedItemComponents = try? container.decode([Int: DestinyBaseItemComponentSetOfuint32].self, forKey: CodingKeys.characterUninstancedItemComponents)
            characters = try? container.decode(DictionaryComponentResponse<Int64, Destiny.Entities.Characters.DestinyCharacterComponent>.self, forKey: CodingKeys.characters)
            itemComponents = try? container.decode(DestinyItemComponentSetOfint64.self, forKey: CodingKeys.itemComponents)
            metrics = try? container.decode(SingleComponentResponse<Destiny.Components.Metrics.DestinyMetricsComponent>.self, forKey: CodingKeys.metrics)
            platformSilver = try? container.decode(SingleComponentResponse<Destiny.Components.Inventory.DestinyPlatformSilverComponent>.self, forKey: CodingKeys.platformSilver)
            profile = try? container.decode(SingleComponentResponse<Destiny.Entities.Profiles.DestinyProfileComponent>.self, forKey: CodingKeys.profile)
            profileCollectibles = try? container.decode(SingleComponentResponse<Destiny.Components.Collectibles.DestinyProfileCollectiblesComponent>.self, forKey: CodingKeys.profileCollectibles)
            profileCommendations = try? container.decode(SingleComponentResponse<Destiny.Components.Social.DestinySocialCommendationsComponent>.self, forKey: CodingKeys.profileCommendations)
            profileCurrencies = try? container.decode(SingleComponentResponse<Destiny.Entities.Inventory.DestinyInventoryComponent>.self, forKey: CodingKeys.profileCurrencies)
            profileInventory = try? container.decode(SingleComponentResponse<Destiny.Entities.Inventory.DestinyInventoryComponent>.self, forKey: CodingKeys.profileInventory)
            profileKiosks = try? container.decode(SingleComponentResponse<Destiny.Components.Kiosks.DestinyKiosksComponent>.self, forKey: CodingKeys.profileKiosks)
            profilePlugSets = try? container.decode(SingleComponentResponse<Destiny.Components.PlugSets.DestinyPlugSetsComponent>.self, forKey: CodingKeys.profilePlugSets)
            profilePresentationNodes = try? container.decode(SingleComponentResponse<Destiny.Components.Presentation.DestinyPresentationNodesComponent>.self, forKey: CodingKeys.profilePresentationNodes)
            profileProgression = try? container.decode(SingleComponentResponse<Destiny.Components.Profiles.DestinyProfileProgressionComponent>.self, forKey: CodingKeys.profileProgression)
            profileRecords = try? container.decode(SingleComponentResponse<Destiny.Components.Records.DestinyProfileRecordsComponent>.self, forKey: CodingKeys.profileRecords)
            profileStringVariables = try? container.decode(SingleComponentResponse<Destiny.Components.StringVariables.DestinyStringVariablesComponent>.self, forKey: CodingKeys.profileStringVariables)
            profileTransitoryData = try? container.decode(SingleComponentResponse<Destiny.Components.Profiles.DestinyProfileTransitoryComponent>.self, forKey: CodingKeys.profileTransitoryData)
            responseMintedTimestamp = try? container.decode(Date.self, forKey: CodingKeys.responseMintedTimestamp)
            secondaryComponentsMintedTimestamp = try? container.decode(Date.self, forKey: CodingKeys.secondaryComponentsMintedTimestamp)
            vendorReceipts = try? container.decode(SingleComponentResponse<Destiny.Entities.Profiles.DestinyVendorReceiptsComponent>.self, forKey: CodingKeys.vendorReceipts)
        }
    }
}
