// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyLinkedProfilesResponse.swift

import Foundation

public extension Destiny.Responses {
    /// I know what you seek. You seek linked accounts. Found them, you have.
    /// This contract returns a minimal amount of data about Destiny Accounts that are linked through your Bungie.Net account. We will not return accounts in this response whose
    struct DestinyLinkedProfilesResponse: Codable {
        /// If the requested membership had a linked Bungie.Net membership ID, this is the basic information about that BNet account.
        /// I know, Tetron; I know this is mixing UserServices concerns with DestinyServices concerns. But it's so damn convenient! https://www.youtube.com/watch?v=X5R-bB-gKVI
        public var bnetMembership: User.UserInfoCard?

        /// Any Destiny account for whom we could successfully pull characters will be returned here, as the Platform-level summary of user data. (no character data, no Destiny account data other than the Membership ID and Type so you can make further queries)
        public var profiles: [Destiny.Responses.DestinyProfileUserInfoCard]?

        /// This is brief summary info for profiles that we believe have valid Destiny info, but who failed to return data for some other reason and thus we know that subsequent calls for their info will also fail.
        public var profilesWithErrors: [Destiny.Responses.DestinyErrorProfile]?

        public enum CodingKeys: String, CodingKey {
            case bnetMembership
            case profiles
            case profilesWithErrors
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            bnetMembership = try? container.decode(User.UserInfoCard.self, forKey: CodingKeys.bnetMembership)
            profiles = try? container.decode([Destiny.Responses.DestinyProfileUserInfoCard].self, forKey: CodingKeys.profiles)
            profilesWithErrors = try? container.decode([Destiny.Responses.DestinyErrorProfile].self, forKey: CodingKeys.profilesWithErrors)
        }
    }
}
