// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyProfileUserInfoCard.swift

import Foundation

public extension Destiny.Responses {
    struct DestinyProfileUserInfoCard: Codable {
        /// The list of Membership Types indicating the platforms on which this Membership can be used.
        ///  Not in Cross Save = its original membership type. Cross Save Primary = Any membership types it is overridding, and its original membership type Cross Save Overridden = Empty list
        public var applicableMembershipTypes: [BungieMembershipType]?

        /// The bungie global display name, if set.
        public var bungieGlobalDisplayName: String?

        /// The bungie global display name code, if set.
        public var bungieGlobalDisplayNameCode: Int16?

        /// If there is a cross save override in effect, this value will tell you the type that is overridding this one.
        public var crossSaveOverride: BungieMembershipType?

        public var dateLastPlayed: Date?

        /// Display Name the player has chosen for themselves. The display name is optional when the data type is used as input to a platform API.
        public var displayName: String?

        /// URL the Icon if available.
        public var iconPath: String?

        /// If true, this account is hooked up as the "Primary" cross save account for one or more platforms.
        public var isCrossSavePrimary: Bool?

        /// If this profile is being overridden/obscured by Cross Save, this will be set to true. We will still return the profile for display purposes where users need to know the info: it is up to any given area of the app/site to determine if this profile should still be shown.
        public var isOverridden: Bool?

        /// If True, this is a public user membership.
        public var isPublic: Bool?

        /// Membership ID as they user is known in the Accounts service
        public var membershipId: Int64?

        /// Type of the membership. Not necessarily the native type.
        public var membershipType: BungieMembershipType?

        /// This is the silver available on this Profile across any platforms on which they have purchased silver.
        ///  This is only available if you are requesting yourself.
        public var platformSilver: Destiny.Components.Inventory.DestinyPlatformSilverComponent?

        /// A platform specific additional display name - ex: psn Real Name, bnet Unique Name, etc.
        public var supplementalDisplayName: String?

        /// If this profile is not in a cross save pairing, this will return the game versions that we believe this profile has access to.
        ///  For the time being, we will not return this information for any membership that is in a cross save pairing. The gist is that, once the pairing occurs, we do not currently have a consistent way to get that information for the profile's original Platform, and thus gameVersions would be too inconsistent (based on the last platform they happened to play on) for the info to be useful.
        ///  If we ever can get this data, this field will be deprecated and replaced with data on the DestinyLinkedProfileResponse itself, with game versions per linked Platform. But since we can't get that, we have this as a stop-gap measure for getting the data in the only situation that we currently need it.
        public var unpairedGameVersions: Int32?

        public enum CodingKeys: String, CodingKey {
            case applicableMembershipTypes
            case bungieGlobalDisplayName
            case bungieGlobalDisplayNameCode
            case crossSaveOverride
            case dateLastPlayed
            case displayName
            case iconPath
            case isCrossSavePrimary
            case isOverridden
            case isPublic
            case membershipId
            case membershipType
            case platformSilver
            case supplementalDisplayName
            case unpairedGameVersions
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            applicableMembershipTypes = try? container.decode([BungieMembershipType].self, forKey: CodingKeys.applicableMembershipTypes)
            bungieGlobalDisplayName = try? container.decode(String.self, forKey: CodingKeys.bungieGlobalDisplayName)
            bungieGlobalDisplayNameCode = try? container.decode(Int16.self, forKey: CodingKeys.bungieGlobalDisplayNameCode)
            crossSaveOverride = try? container.decode(BungieMembershipType.self, forKey: CodingKeys.crossSaveOverride)
            dateLastPlayed = try? container.decode(Date.self, forKey: CodingKeys.dateLastPlayed)
            displayName = try? container.decode(String.self, forKey: CodingKeys.displayName)
            iconPath = try? container.decode(String.self, forKey: CodingKeys.iconPath)
            isCrossSavePrimary = try? container.decode(Bool.self, forKey: CodingKeys.isCrossSavePrimary)
            isOverridden = try? container.decode(Bool.self, forKey: CodingKeys.isOverridden)
            isPublic = try? container.decode(Bool.self, forKey: CodingKeys.isPublic)
            let membershipId = try? container.decode(String.self, forKey: CodingKeys.membershipId)
            if let membershipId, let membershipIdInt = Int64(membershipId) {
                self.membershipId = membershipIdInt
            } else {
                self.membershipId = nil
            }
            membershipType = try? container.decode(BungieMembershipType.self, forKey: CodingKeys.membershipType)
            platformSilver = try? container.decode(Destiny.Components.Inventory.DestinyPlatformSilverComponent.self, forKey: CodingKeys.platformSilver)
            supplementalDisplayName = try? container.decode(String.self, forKey: CodingKeys.supplementalDisplayName)
            unpairedGameVersions = try? container.decode(Int32.self, forKey: CodingKeys.unpairedGameVersions)
        }
    }
}
