// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyArtifactTierItemDefinition.swift

import Foundation

public extension Destiny.Definitions.Artifacts {
    struct DestinyArtifactTierItemDefinition: Codable {
        /// The identifier of the Plug Item unlocked by activating this item in the Artifact.
        public var itemHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case itemHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            itemHash = try? container.decode(UInt32.self, forKey: CodingKeys.itemHash)
        }
    }
}
