// This File was auto generated by BungoKitGen
//
// File: DestinyMetricComponent.swift

import Foundation

public extension Destiny.Components.Metrics {
    struct DestinyMetricComponent: Codable {
        public var invisible: Bool?
        public var objectiveProgress: Destiny.Quests.DestinyObjectiveProgress?

        public enum CodingKeys: String, CodingKey {
            case invisible
            case objectiveProgress
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            invisible = try? container.decode(Bool.self, forKey: CodingKeys.invisible)
            objectiveProgress = try? container.decode(Destiny.Quests.DestinyObjectiveProgress.self, forKey: CodingKeys.objectiveProgress)
        }
    }
}
