// This File was auto generated by BungoKitGen
//
// File: ClanBannerDecal.swift

import Foundation

public extension Config.ClanBanner {
    struct ClanBannerDecal: Codable {
        public var backgroundPath: String?
        public var foregroundPath: String?
        public var identifier: String?

        public enum CodingKeys: String, CodingKey {
            case backgroundPath
            case foregroundPath
            case identifier
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            backgroundPath = try? container.decode(String.self, forKey: CodingKeys.backgroundPath)
            foregroundPath = try? container.decode(String.self, forKey: CodingKeys.foregroundPath)
            identifier = try? container.decode(String.self, forKey: CodingKeys.identifier)
        }
    }
}
