// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: ClanBannerSource.swift

import Foundation

public extension Config.ClanBanner {
    struct ClanBannerSource: Codable {}
}
