// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinySocketTypeDefinition.swift

import Foundation

public extension Destiny.Definitions.Sockets {
    /// All Sockets have a "Type": a set of common properties that determine when the socket allows Plugs to be inserted, what Categories of Plugs can be inserted, and whether the socket is even visible at all given the current game/character/account state.
    /// See DestinyInventoryItemDefinition for more information about Socketed items and Plugs.
    struct DestinySocketTypeDefinition: Codable {
        public var alwaysRandomizeSockets: Bool?

        public var avoidDuplicatesOnInitialization: Bool?

        public var currencyScalars: [Destiny.Definitions.Sockets.DestinySocketTypeScalarMaterialRequirementEntry]?

        /// There are fields for this display data, but they appear to be unpopulated as of now. I am not sure where in the UI these would show if they even were populated, but I will continue to return this data in case it becomes useful.
        public var displayProperties: Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition?

        /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
        /// When entities refer to each other in Destiny content, it is this hash that they are referring to.
        public var hash: UInt32?

        public var hideDuplicateReusablePlugs: Bool?

        /// The index of the entity as it was found in the investment tables.
        public var index: Int32?

        /// Defines what happens when a plug is inserted into sockets of this type.
        public var insertAction: Destiny.Definitions.Sockets.DestinyInsertPlugActionDefinition?

        public var isPreviewEnabled: Bool?

        /// This property indicates if the socket type determines whether Emblem icons and nameplates should be overridden by the inserted plug item's icon and nameplate.
        public var overridesUiAppearance: Bool?

        /// A list of Plug "Categories" that are allowed to be plugged into sockets of this type.
        /// These should be compared against a given plug item's DestinyInventoryItemDefinition.plug.plugCategoryHash, which indicates the plug item's category.
        /// If the plug's category matches any whitelisted plug, or if the whitelist is empty, it is allowed to be inserted.
        public var plugWhitelist: [Destiny.Definitions.Sockets.DestinyPlugWhitelistEntryDefinition]?

        /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
        public var redacted: Bool?

        public var socketCategoryHash: UInt32?

        /// Sometimes a socket isn't visible. These are some of the conditions under which sockets of this type are not visible. Unfortunately, the truth of visibility is much, much more complex. Best to rely on the live data for whether the socket is visible and enabled.
        public var visibility: Destiny.DestinySocketVisibility?

        public enum CodingKeys: String, CodingKey {
            case alwaysRandomizeSockets
            case avoidDuplicatesOnInitialization
            case currencyScalars
            case displayProperties
            case hash
            case hideDuplicateReusablePlugs
            case index
            case insertAction
            case isPreviewEnabled
            case overridesUiAppearance
            case plugWhitelist
            case redacted
            case socketCategoryHash
            case visibility
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            alwaysRandomizeSockets = try? container.decode(Bool.self, forKey: CodingKeys.alwaysRandomizeSockets)
            avoidDuplicatesOnInitialization = try? container.decode(Bool.self, forKey: CodingKeys.avoidDuplicatesOnInitialization)
            currencyScalars = try? container.decode([Destiny.Definitions.Sockets.DestinySocketTypeScalarMaterialRequirementEntry].self, forKey: CodingKeys.currencyScalars)
            displayProperties = try? container.decode(Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition.self, forKey: CodingKeys.displayProperties)
            hash = try? container.decode(UInt32.self, forKey: CodingKeys.hash)
            hideDuplicateReusablePlugs = try? container.decode(Bool.self, forKey: CodingKeys.hideDuplicateReusablePlugs)
            index = try? container.decode(Int32.self, forKey: CodingKeys.index)
            insertAction = try? container.decode(Destiny.Definitions.Sockets.DestinyInsertPlugActionDefinition.self, forKey: CodingKeys.insertAction)
            isPreviewEnabled = try? container.decode(Bool.self, forKey: CodingKeys.isPreviewEnabled)
            overridesUiAppearance = try? container.decode(Bool.self, forKey: CodingKeys.overridesUiAppearance)
            plugWhitelist = try? container.decode([Destiny.Definitions.Sockets.DestinyPlugWhitelistEntryDefinition].self, forKey: CodingKeys.plugWhitelist)
            redacted = try? container.decode(Bool.self, forKey: CodingKeys.redacted)
            socketCategoryHash = try? container.decode(UInt32.self, forKey: CodingKeys.socketCategoryHash)
            visibility = try? container.decode(Destiny.DestinySocketVisibility.self, forKey: CodingKeys.visibility)
        }
    }
}
