// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: ForumRecruitmentIntensityLabel.swift

import Foundation

public extension Forum {
    enum ForumRecruitmentIntensityLabel: UInt32, Codable {
        case none = 0
        case casual = 1
        case professional = 2
    }
}
