// This File was auto generated by BungieAPIGen
//
// ForumTopicsQuickDateEnum.swift

import Foundation

public extension Forum {
    enum ForumTopicsQuickDateEnum: Int32, Codable {
        case all = 0
        case lastYear = 1
        case lastMonth = 2
        case lastWeek = 3
        case lastDay = 4
    }
}
