// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: ForumTopicsCategoryFiltersEnum.swift

import Foundation

public extension Forum {
    enum ForumTopicsCategoryFiltersEnum: Int32, Codable {
        case none = 0
        case links = 1
        case questions = 2
        case answeredQuestions = 4
        case media = 8
        case textOnly = 16
        case announcement = 32
        case bungieOfficial = 64
        case polls = 128
    }
}
