// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: BucketCategory.swift

import Foundation

public extension Destiny {
    enum BucketCategory: Int32, Codable {
        case invisible = 0
        case item = 1
        case currency = 2
        case equippable = 3
        case ignored = 4
    }
}
