// This File was auto generated by BungieAPIGen
//
// DestinyStatCategory.swift

import Foundation

public extension Destiny {
    /// At last, stats have categories. Use this for whatever purpose you might wish.
    enum DestinyStatCategory: Int32, Codable {
        case gameplay = 0
        case weapon = 1
        case defense = 2
        case primary = 3
    }
}
