// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyGender.swift

import Foundation

public extension Destiny {
    enum DestinyGender: Int32, Codable {
        case male = 0
        case female = 1
        case unknown = 2
    }
}
