// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyStatAggregationType.swift

import Foundation

public extension Destiny {
    /// When a Stat (DestinyStatDefinition) is aggregated, this is the rules used for determining the level and formula used for aggregation.
    /// * CharacterAverage = apply a weighted average using the related DestinyStatGroupDefinition on the DestinyInventoryItemDefinition across the character's equipped items. See both of those definitions for details. * Character = don't aggregate: the stat should be located and used directly on the character. * Item = don't aggregate: the stat should be located and used directly on the item.
    enum DestinyStatAggregationType: Int32, Codable {
        case characterAverage = 0
        case character = 1
        case item = 2
    }
}
