// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyEnergyType.swift

import Foundation

public extension Destiny {
    /// Represents the socket energy types for Armor 2.0, Ghosts 2.0, and Stasis subclasses.
    enum DestinyEnergyType: Int32, Codable {
        case any = 0
        case arc = 1
        case thermal = 2
        case void = 3
        case ghost = 4
        case subclass = 5
        case stasis = 6
    }
}
