// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyClass.swift

import Foundation

public extension Destiny {
    enum DestinyClass: Int32, Codable {
        case titan = 0
        case hunter = 1
        case warlock = 2
        case unknown = 3
    }
}
