// This File was auto generated by BungieAPIGen
//
// DestinyPresentationNodeType.swift

import Foundation

public extension Destiny {
    enum DestinyPresentationNodeType: Int32, Codable {
        case `default` = 0
        case category = 1
        case collectibles = 2
        case records = 3
        case metric = 4
        case craftable = 5
    }
}
