// This File was auto generated by BungieAPIGen
//
// DestinyRecordState.swift

import Foundation

public extension Destiny {
    /// A Flags enumeration/bitmask where each bit represents a possible state that a Record/Triumph can be in.
    enum DestinyRecordState: Int32, Codable {
        /// If there are no flags set, the record is in a state where it *could* be redeemed, but it has not been yet.
        case none = 0
        /// If this is set, the completed record has been redeemed.
        case recordRedeemed = 1
        /// If this is set, there's a reward available from this Record but it's unavailable for redemption.
        case rewardUnavailable = 2
        /// If this is set, the objective for this Record has not yet been completed.
        case objectiveNotCompleted = 4
        /// If this is set, the game recommends that you replace the display text of this Record with DestinyRecordDefinition.stateInfo.obscuredString.
        case obscured = 8
        /// If this is set, the game recommends that you not show this record. Do what you will with this recommendation.
        case invisible = 16
        /// If this is set, you can't complete this record because you lack some permission that's required to complete it.
        case entitlementUnowned = 32
        /// If this is set, the record has a title (check DestinyRecordDefinition for title info) and you can equip it.
        case canEquipTitle = 64
    }
}
