// This File was auto generated by BungieAPIGen
//
// DestinyProgressionRewardItemAcquisitionBehavior.swift

import Foundation

public extension Destiny {
    /// Represents the different kinds of acquisition behavior for progression reward items.
    enum DestinyProgressionRewardItemAcquisitionBehavior: Int32, Codable {
        case instant = 0
        case playerClaimRequired = 1
    }
}
