// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyVendorReplyType.swift

import Foundation

public extension Destiny {
    /// This determines the type of reply that a Vendor will have during an Interaction.
    enum DestinyVendorReplyType: Int32, Codable {
        case accept = 0
        case decline = 1
        case complete = 2
    }
}
