// This File was auto generated by BungoKitGen
//
// File: DestinyProgressionResetEntry.swift

import Foundation

public extension Destiny {
    /// Represents a season and the number of resets you had in that season.
    ///  We do not necessarily - even for progressions with resets - track it over all seasons. So be careful and check the season numbers being returned.
    struct DestinyProgressionResetEntry: Codable {
        public var resets: Int32?
        public var season: Int32?

        public enum CodingKeys: String, CodingKey {
            case resets
            case season
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            resets = try? container.decode(Int32.self, forKey: CodingKeys.resets)
            season = try? container.decode(Int32.self, forKey: CodingKeys.season)
        }
    }
}
