// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyProgressionStepDisplayEffect.swift

import Foundation

public extension Destiny {
    /// If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.
    enum DestinyProgressionStepDisplayEffect: Int32, Codable {
        case none = 0
        case character = 1
        case item = 2
    }
}
