// This File was auto generated by BungieAPIGen
//
// EquippingItemBlockAttributes.swift

import Foundation

public extension Destiny {
    enum EquippingItemBlockAttributes: Int32, Codable {
        case none = 0
        case equipOnAcquire = 1
    }
}
