// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: PlugUiStyles.swift

import Foundation

public extension Destiny {
    /// If the plug has a specific custom style, this enumeration will represent that style/those styles.
    enum PlugUiStyles: Int32, Codable {
        case none = 0
        case masterwork = 1
    }
}
