// This File was auto generated by BungieAPIGen
//
// SocketTypeActionType.swift

import Foundation

public extension Destiny {
    /// Indicates the type of actions that can be performed
    enum SocketTypeActionType: Int32, Codable {
        case insertPlug = 0
        case infuseItem = 1
        case reinitializeSocket = 2
    }
}
