// This File was auto generated by BungieAPIGen
//
// TierType.swift

import Foundation

public extension Destiny {
    enum TierType: Int32, Codable {
        case unknown = 0
        case currency = 1
        case basic = 2
        case common = 3
        case rare = 4
        case superior = 5
        case exotic = 6
    }
}
