// This File was auto generated by BungieAPIGen
//
// VendorItemStatus.swift

import Foundation

public extension Destiny {
    enum VendorItemStatus: Int32, Codable {
        case success = 0
        case noInventorySpace = 1
        case noFunds = 2
        case noProgression = 4
        case noUnlock = 8
        case noQuantity = 16
        case outsidePurchaseWindow = 32
        case notAvailable = 64
        case uniquenessViolation = 128
        case unknownError = 256
        case alreadySelling = 512
        case unsellable = 1024
        case sellingInhibited = 2048
        case alreadyOwned = 4096
        case displayOnly = 8192
    }
}
