// This File was auto generated by BungieAPIGen
//
// VendorDisplayCategorySortOrder.swift

import Foundation

public extension Destiny {
    /// Display categories can have custom sort orders. These are the possible options.
    enum VendorDisplayCategorySortOrder: Int32, Codable {
        case `default` = 0
        case sortByTier = 1
    }
}
