// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: BungieFriendRequestListResponse.swift

import Foundation

public extension Social.Friends {
    struct BungieFriendRequestListResponse: Codable {
        public var incomingRequests: [Social.Friends.BungieFriend]?

        public var outgoingRequests: [Social.Friends.BungieFriend]?

        public enum CodingKeys: String, CodingKey {
            case incomingRequests
            case outgoingRequests
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            incomingRequests = try? container.decode([Social.Friends.BungieFriend].self, forKey: CodingKeys.incomingRequests)
            outgoingRequests = try? container.decode([Social.Friends.BungieFriend].self, forKey: CodingKeys.outgoingRequests)
        }
    }
}
