// This File was auto generated by BungoKitGen
//
// File: BungieFriend.swift

import Foundation

public extension Social.Friends {
    struct BungieFriend: Codable {
        public var bungieGlobalDisplayName: String?
        public var bungieGlobalDisplayNameCode: Int16?
        public var bungieNetUser: User.GeneralUser?
        public var lastSeenAsBungieMembershipType: BungieMembershipType?
        public var lastSeenAsMembershipId: Int64?
        public var onlineStatus: Social.Friends.PresenceStatus?
        public var onlineTitle: Social.Friends.PresenceOnlineStateFlags?
        public var relationship: Social.Friends.FriendRelationshipState?

        public enum CodingKeys: String, CodingKey {
            case bungieGlobalDisplayName
            case bungieGlobalDisplayNameCode
            case bungieNetUser
            case lastSeenAsBungieMembershipType
            case lastSeenAsMembershipId
            case onlineStatus
            case onlineTitle
            case relationship
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            bungieGlobalDisplayName = try? container.decode(String.self, forKey: CodingKeys.bungieGlobalDisplayName)
            bungieGlobalDisplayNameCode = try? container.decode(Int16.self, forKey: CodingKeys.bungieGlobalDisplayNameCode)
            bungieNetUser = try? container.decode(User.GeneralUser.self, forKey: CodingKeys.bungieNetUser)
            lastSeenAsBungieMembershipType = try? container.decode(BungieMembershipType.self, forKey: CodingKeys.lastSeenAsBungieMembershipType)
            let lastSeenAsMembershipId = try? container.decode(String.self, forKey: CodingKeys.lastSeenAsMembershipId)
            if let lastSeenAsMembershipId, let lastSeenAsMembershipIdInt = Int64(lastSeenAsMembershipId) {
                self.lastSeenAsMembershipId = lastSeenAsMembershipIdInt
            } else {
                self.lastSeenAsMembershipId = nil
            }
            onlineStatus = try? container.decode(Social.Friends.PresenceStatus.self, forKey: CodingKeys.onlineStatus)
            onlineTitle = try? container.decode(Social.Friends.PresenceOnlineStateFlags.self, forKey: CodingKeys.onlineTitle)
            relationship = try? container.decode(Social.Friends.FriendRelationshipState.self, forKey: CodingKeys.relationship)
        }
    }
}
