// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: PlatformFriendType.swift

import Foundation

public extension Social.Friends {
    enum PlatformFriendType: Int32, Codable {
        case unknown = 0
        case xbox = 1
        case pSN = 2
        case steam = 3
        case egs = 4
    }
}
