// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: PresenceStatus.swift

import Foundation

public extension Social.Friends {
    enum PresenceStatus: Int32, Codable {
        case offlineOrUnknown = 0
        case online = 1
    }
}
