// This File was auto generated by BungoKitGen
//
// File: DestinyRecordIntervalBlock.swift

import Foundation

public extension Destiny.Definitions.Records {
    struct DestinyRecordIntervalBlock: Codable {
        public var intervalObjectives: [Destiny.Definitions.Records.DestinyRecordIntervalObjective]?
        public var intervalRewards: [Destiny.Definitions.Records.DestinyRecordIntervalRewards]?
        public var originalObjectiveArrayInsertionIndex: Int32?

        public enum CodingKeys: String, CodingKey {
            case intervalObjectives
            case intervalRewards
            case originalObjectiveArrayInsertionIndex
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            intervalObjectives = try? container.decode([Destiny.Definitions.Records.DestinyRecordIntervalObjective].self, forKey: CodingKeys.intervalObjectives)
            intervalRewards = try? container.decode([Destiny.Definitions.Records.DestinyRecordIntervalRewards].self, forKey: CodingKeys.intervalRewards)
            originalObjectiveArrayInsertionIndex = try? container.decode(Int32.self, forKey: CodingKeys.originalObjectiveArrayInsertionIndex)
        }
    }
}
