// This File was auto generated by BungoKitGen
//
// File: DestinyRecordIntervalObjective.swift

import Foundation

public extension Destiny.Definitions.Records {
    struct DestinyRecordIntervalObjective: Codable {
        public var intervalObjectiveHash: UInt32?
        public var intervalScoreValue: Int32?

        public enum CodingKeys: String, CodingKey {
            case intervalObjectiveHash
            case intervalScoreValue
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            intervalObjectiveHash = try? container.decode(UInt32.self, forKey: CodingKeys.intervalObjectiveHash)
            intervalScoreValue = try? container.decode(Int32.self, forKey: CodingKeys.intervalScoreValue)
        }
    }
}
