// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: ImagePyramidEntry.swift

import Foundation

public extension Destiny.Config {
    struct ImagePyramidEntry: Codable {
        /// The factor by which the original image size has been reduced.
        public var factor: Float?

        /// The name of the subfolder where these images are located.
        public var name: String?

        public enum CodingKeys: String, CodingKey {
            case factor
            case name
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            factor = try? container.decode(Float.self, forKey: CodingKeys.factor)
            name = try? container.decode(String.self, forKey: CodingKeys.name)
        }
    }
}
