// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: IgnoreLength.swift

import Foundation

public extension Ignores {
    enum IgnoreLength: Int32, Codable {
        case none = 0
        case week = 1
        case twoWeeks = 2
        case threeWeeks = 3
        case month = 4
        case threeMonths = 5
        case sixMonths = 6
        case year = 7
        case forever = 8
        case threeMinutes = 9
        case hour = 10
        case thirtyDays = 11
    }
}
