// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: FireteamDateRange.swift

import Foundation

public extension Fireteam {
    enum FireteamDateRange: UInt32, Codable {
        case all = 0
        case now = 1
        case twentyFourHours = 2
        case fortyEightHours = 3
        case thisWeek = 4
    }
}
