// This File was auto generated by BungieAPIGen
//
// FireteamPlatform.swift

import Foundation

public extension Fireteam {
    enum FireteamPlatform: UInt32, Codable {
        case any = 0
        case playstation4 = 1
        case xboxOne = 2
        case blizzard = 3
        case steam = 4
        case stadia = 5
        case egs = 6
    }
}
