// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetFriendRequestList.swift

import Foundation

public extension Requests.Social {
    /// Returns your friend request queue.
    struct GetFriendRequestListRequest: BungoRequest {
        public typealias Response = Social.Friends.BungieFriendRequestListResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Social/Friends/Requests/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init() {
            parameters = .init()
        }
    }
}
