// This File was auto generated by BungoKitGen
//
// File: DestinyItemPeerView.swift

import Foundation

public extension Destiny.Character {
    /// Bare minimum summary information for an item, for the sake of 3D rendering the item.
    struct DestinyItemPeerView: Codable {
        /// The list of dyes that have been applied to this item.
        public var dyes: [Destiny.DyeReference]?
        /// The hash identifier of the item in question. Use it to look up the DestinyInventoryItemDefinition of the item for static rendering data.
        public var itemHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case dyes
            case itemHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            dyes = try? container.decode([Destiny.DyeReference].self, forKey: CodingKeys.dyes)
            itemHash = try? container.decode(UInt32.self, forKey: CodingKeys.itemHash)
        }
    }
}
