// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyVendorSaleItemSetComponentOfDestinyPublicVendorSaleItemComponent.swift

import Foundation

public struct DestinyVendorSaleItemSetComponentOfDestinyPublicVendorSaleItemComponent: Codable {
    public var saleItems: [Int32: Destiny.Components.Vendors.DestinyPublicVendorSaleItemComponent]?

    public enum CodingKeys: String, CodingKey {
        case saleItems
    }

    public init(from decoder: Decoder) throws {
        let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

        saleItems = try? container.decode([Int32: Destiny.Components.Vendors.DestinyPublicVendorSaleItemComponent].self, forKey: CodingKeys.saleItems)
    }
}
