// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GlobalAlertLevel.swift

import Foundation

public enum GlobalAlertLevel: Int32, Codable {
    case unknown = 0
    case blue = 1
    case yellow = 2
    case red = 3
}
