// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyItemSourceDefinition.swift

import Foundation

public extension Destiny.Definitions.Sources {
    /// Properties of a DestinyInventoryItemDefinition that store all of the information we were able to discern about how the item spawns, and where you can find the item.
    /// Items will have many of these sources, one per level at which it spawns, to try and give more granular data about where items spawn for specific level ranges.
    struct DestinyItemSourceDefinition: Codable {
        /// The stats computed for this level/quality range.
        public var computedStats: [UInt32: Destiny.Definitions.DestinyInventoryItemStatDefinition]?

        /// The level at which the item spawns. Essentially the Primary Key for this source data: there will be multiple of these source entries per item that has source data, grouped by the level at which the item spawns.
        public var level: Int32?

        /// The maximum Character Level required for equipping the item when the item spawns at the item level defined on this DestinyItemSourceDefinition, as far as we saw in our processing.
        public var maxLevelRequired: Int32?

        /// The maximum quality at which the item spawns for this level.
        public var maxQuality: Int32?

        /// The minimum Character Level required for equipping the item when the item spawns at the item level defined on this DestinyItemSourceDefinition, as far as we saw in our processing.
        public var minLevelRequired: Int32?

        /// The minimum Quality at which the item spawns for this level. Examine DestinyInventoryItemDefinition for more information about what Quality means. Just don't ask Phaedrus about it, he'll never stop talking and you'll have to write a book about it.
        public var minQuality: Int32?

        /// The DestinyRewardSourceDefinitions found that can spawn the item at this level.
        public var sourceHashes: [UInt32]?

        public enum CodingKeys: String, CodingKey {
            case computedStats
            case level
            case maxLevelRequired
            case maxQuality
            case minLevelRequired
            case minQuality
            case sourceHashes
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            let rawcomputedStats = try? container.decode([String: Destiny.Definitions.DestinyInventoryItemStatDefinition].self, forKey: CodingKeys.computedStats)
            computedStats = rawcomputedStats?.compactMapKeys { key, _ -> UInt32? in
                UInt32(key)
            }
            level = try? container.decode(Int32.self, forKey: CodingKeys.level)
            maxLevelRequired = try? container.decode(Int32.self, forKey: CodingKeys.maxLevelRequired)
            maxQuality = try? container.decode(Int32.self, forKey: CodingKeys.maxQuality)
            minLevelRequired = try? container.decode(Int32.self, forKey: CodingKeys.minLevelRequired)
            minQuality = try? container.decode(Int32.self, forKey: CodingKeys.minQuality)
            sourceHashes = try? container.decode([UInt32].self, forKey: CodingKeys.sourceHashes)
        }
    }
}
