// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyHistoricalStatsValuePair.swift

import Foundation

public extension Destiny.HistoricalStats {
    struct DestinyHistoricalStatsValuePair: Codable {
        /// Localized formated version of the value.
        public var displayValue: String?

        /// Raw value of the statistic
        public var value: Double?

        public enum CodingKeys: String, CodingKey {
            case displayValue
            case value
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            displayValue = try? container.decode(String.self, forKey: CodingKeys.displayValue)
            value = try? container.decode(Double.self, forKey: CodingKeys.value)
        }
    }
}
