// This File was auto generated by BungoKitGen
//
// File: DestinyPostGameCarnageReportData.swift

import Foundation

public extension Destiny.HistoricalStats {
    struct DestinyPostGameCarnageReportData: Codable {
        /// Details about the activity.
        public var activityDetails: Destiny.HistoricalStats.DestinyHistoricalStatsActivity?
        /// True if the activity was started from the beginning, if that information is available and the activity was played post Witch Queen release.
        public var activityWasStartedFromBeginning: Bool?
        /// Collection of players and their data for this activity.
        public var entries: [Destiny.HistoricalStats.DestinyPostGameCarnageReportEntry]?
        /// Date and time for the activity.
        public var period: Date?
        /// If this activity has "phases", this is the phase at which the activity was started. This value is only valid for activities before the Beyond Light expansion shipped. Subsequent activities will not have a valid value here.
        public var startingPhaseIndex: Int32?
        /// Collection of stats for the player in this activity.
        public var teams: [Destiny.HistoricalStats.DestinyPostGameCarnageReportTeamEntry]?

        public enum CodingKeys: String, CodingKey {
            case activityDetails
            case activityWasStartedFromBeginning
            case entries
            case period
            case startingPhaseIndex
            case teams
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            activityDetails = try? container.decode(Destiny.HistoricalStats.DestinyHistoricalStatsActivity.self, forKey: CodingKeys.activityDetails)
            activityWasStartedFromBeginning = try? container.decode(Bool.self, forKey: CodingKeys.activityWasStartedFromBeginning)
            entries = try? container.decode([Destiny.HistoricalStats.DestinyPostGameCarnageReportEntry].self, forKey: CodingKeys.entries)
            period = try? container.decode(Date.self, forKey: CodingKeys.period)
            startingPhaseIndex = try? container.decode(Int32.self, forKey: CodingKeys.startingPhaseIndex)
            teams = try? container.decode([Destiny.HistoricalStats.DestinyPostGameCarnageReportTeamEntry].self, forKey: CodingKeys.teams)
        }
    }
}
