// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: EMailSettingSubscriptionLocalization.swift

import Foundation

public extension User {
    /// Localized text relevant to a given EMail setting in a given localization. Extra settings specifically for subscriptions.
    struct EMailSettingSubscriptionLocalization: Codable {
        public var description: String?

        public var knownUserActionText: String?

        public var registeredUserDescription: String?

        public var title: String?

        public var unknownUserActionText: String?

        public var unknownUserDescription: String?

        public var unregisteredUserDescription: String?

        public enum CodingKeys: String, CodingKey {
            case description
            case knownUserActionText
            case registeredUserDescription
            case title
            case unknownUserActionText
            case unknownUserDescription
            case unregisteredUserDescription
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            description = try? container.decode(String.self, forKey: CodingKeys.description)
            knownUserActionText = try? container.decode(String.self, forKey: CodingKeys.knownUserActionText)
            registeredUserDescription = try? container.decode(String.self, forKey: CodingKeys.registeredUserDescription)
            title = try? container.decode(String.self, forKey: CodingKeys.title)
            unknownUserActionText = try? container.decode(String.self, forKey: CodingKeys.unknownUserActionText)
            unknownUserDescription = try? container.decode(String.self, forKey: CodingKeys.unknownUserDescription)
            unregisteredUserDescription = try? container.decode(String.self, forKey: CodingKeys.unregisteredUserDescription)
        }
    }
}
