// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: EMailSettingLocalization.swift

import Foundation

public extension User {
    /// Localized text relevant to a given EMail setting in a given localization.
    struct EMailSettingLocalization: Codable {
        public var description: String?

        public var title: String?

        public enum CodingKeys: String, CodingKey {
            case description
            case title
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            description = try? container.decode(String.self, forKey: CodingKeys.description)
            title = try? container.decode(String.self, forKey: CodingKeys.title)
        }
    }
}
