// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: EmailSettings.swift

import Foundation

public extension User {
    /// The set of all email subscription/opt-in settings and definitions.
    struct EmailSettings: Codable {
        /// Keyed by the name identifier of the opt-in definition.
        public var optInDefinitions: [String: User.EmailOptInDefinition]?

        /// Keyed by the name identifier of the Subscription definition.
        public var subscriptionDefinitions: [String: User.EmailSubscriptionDefinition]?

        /// Keyed by the name identifier of the View definition.
        public var views: [String: User.EmailViewDefinition]?

        public enum CodingKeys: String, CodingKey {
            case optInDefinitions
            case subscriptionDefinitions
            case views
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            optInDefinitions = try? container.decode([String: User.EmailOptInDefinition].self, forKey: CodingKeys.optInDefinitions)
            subscriptionDefinitions = try? container.decode([String: User.EmailSubscriptionDefinition].self, forKey: CodingKeys.subscriptionDefinitions)
            views = try? container.decode([String: User.EmailViewDefinition].self, forKey: CodingKeys.views)
        }
    }
}
