// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: OptInFlags.swift

import Foundation

public extension User {
    enum OptInFlags: UInt64, Codable {
        case none = 0
        case newsletter = 1
        case system = 2
        case marketing = 4
        case userResearch = 8
        case customerService = 16
        case social = 32
        case playTests = 64
        case playTestsLocal = 128
        case careers = 256
    }
}
