// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: UserMembershipData.swift

import Foundation

public extension User {
    struct UserMembershipData: Codable {
        public var bungieNetUser: User.GeneralUser?

        /// this allows you to see destiny memberships that are visible and linked to this account (regardless of whether or not they have characters on the world server)
        public var destinyMemberships: [GroupsV2.GroupUserInfoCard]?

        /// If this property is populated, it will have the membership ID of the account considered to be "primary" in this user's cross save relationship.
        ///  If null, this user has no cross save relationship, nor primary account.
        public var primaryMembershipId: Int64?

        public enum CodingKeys: String, CodingKey {
            case bungieNetUser
            case destinyMemberships
            case primaryMembershipId
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            bungieNetUser = try? container.decode(User.GeneralUser.self, forKey: CodingKeys.bungieNetUser)
            destinyMemberships = try? container.decode([GroupsV2.GroupUserInfoCard].self, forKey: CodingKeys.destinyMemberships)
            let primaryMembershipId = try? container.decode(String.self, forKey: CodingKeys.primaryMembershipId)
            if let primaryMembershipId, let primaryMembershipIdInt = Int64(primaryMembershipId) {
                self.primaryMembershipId = primaryMembershipIdInt
            } else {
                self.primaryMembershipId = nil
            }
        }
    }
}
