// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: UserToUserContext.swift

import Foundation

public extension User {
    struct UserToUserContext: Codable {
        public var globalIgnoreEndDate: Date?

        public var ignoreStatus: Ignores.IgnoreResponse?

        public var isFollowing: Bool?

        public enum CodingKeys: String, CodingKey {
            case globalIgnoreEndDate
            case ignoreStatus
            case isFollowing
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            globalIgnoreEndDate = try? container.decode(Date.self, forKey: CodingKeys.globalIgnoreEndDate)
            ignoreStatus = try? container.decode(Ignores.IgnoreResponse.self, forKey: CodingKeys.ignoreStatus)
            isFollowing = try? container.decode(Bool.self, forKey: CodingKeys.isFollowing)
        }
    }
}
