// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: BungieRewardDisplay.swift

import Foundation

public extension Tokens {
    struct BungieRewardDisplay: Codable {
        public var objectiveDisplayProperties: Tokens.RewardDisplayProperties?

        public var rewardDisplayProperties: Tokens.RewardDisplayProperties?

        public var userRewardAvailabilityModel: Tokens.UserRewardAvailabilityModel?

        public enum CodingKeys: String, CodingKey {
            case objectiveDisplayProperties = "ObjectiveDisplayProperties"
            case rewardDisplayProperties = "RewardDisplayProperties"
            case userRewardAvailabilityModel = "UserRewardAvailabilityModel"
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            objectiveDisplayProperties = try? container.decode(Tokens.RewardDisplayProperties.self, forKey: CodingKeys.objectiveDisplayProperties)
            rewardDisplayProperties = try? container.decode(Tokens.RewardDisplayProperties.self, forKey: CodingKeys.rewardDisplayProperties)
            userRewardAvailabilityModel = try? container.decode(Tokens.UserRewardAvailabilityModel.self, forKey: CodingKeys.userRewardAvailabilityModel)
        }
    }
}
