// This File was auto generated by BungoKitGen
//
// File: AwaGetActionToken.swift

import Foundation

public extension Requests.Destiny2 {
    /// Returns the action token if user approves the request.
    struct AwaGetActionTokenRequest: BungoRequest {
        public typealias Response = Destiny.Advanced.AwaAuthorizationResult

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(correlationId: String) {
                query = [:]
                path = [:]

                path["correlationId"] = "\(correlationId)"
            }
        }

        public let path = "/Destiny2/Awa/GetActionToken/{correlationId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
