// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: AwaInitializeRequest.swift

import Foundation

public extension Requests.Destiny2 {
    /// Initialize a request to perform an advanced write action.
    struct AwaInitializeRequestRequest: BungoRequest {
        public typealias Response = Destiny.Advanced.AwaInitializeResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Destiny2/Awa/Initialize/"
        public let parameters: Parameters
        public let method: HTTPMethod = .post
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
