// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetClanBannerSource.swift

import Foundation

public extension Requests.Destiny2 {
    /// Returns the dictionary of values for the Clan Banner
    struct GetClanBannerSourceRequest: BungoRequest {
        public typealias Response = Config.ClanBanner.ClanBannerSource

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Destiny2/Clan/ClanBannerDictionary/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
