// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetCollectibleNodeDetails.swift

import Foundation

public extension Requests.Destiny2 {
    /// Given a Presentation Node that has Collectibles as direct descendants, this will return item details about those descendants in the context of the requesting character.
    struct GetCollectibleNodeDetailsRequest: BungoRequest {
        public typealias Response = Destiny.Responses.DestinyCollectibleNodeDetailResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(characterId: Int64, collectiblePresentationNodeHash: UInt32, destinyMembershipId: Int64, membershipType: BungieMembershipType, components: Destiny.DestinyComponentType...) {
                query = [:]
                path = [:]

                query["components"] = "\(components.map { "\($0.rawValue)" }.joined(separator: ","))"

                path["characterId"] = "\(characterId)"
                path["collectiblePresentationNodeHash"] = "\(collectiblePresentationNodeHash)"
                path["destinyMembershipId"] = "\(destinyMembershipId)"
                path["membershipType"] = "\(membershipType.rawValue)"
            }
        }

        public let path = "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Collectibles/{collectiblePresentationNodeHash}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
