// This File was auto generated by BungoKitGen
//
// File: GetHistoricalStatsDefinition.swift

import AnyCodable
import Foundation
public extension Requests.Destiny2 {
    /// Gets historical stats definitions.
    struct GetHistoricalStatsDefinitionRequest: BungoRequest {
        public typealias Response = AnyCodable

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Destiny2/Stats/Definition/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
