// This File was auto generated by BungoKitGen
//
// File: GetPublicMilestoneContent.swift

import Foundation

public extension Requests.Destiny2 {
    /// Gets custom localized content for the milestone of the given hash, if it exists.
    struct GetPublicMilestoneContentRequest: BungoRequest {
        public typealias Response = Destiny.Milestones.DestinyMilestoneContent

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(milestoneHash: UInt32) {
                query = [:]
                path = [:]

                path["milestoneHash"] = "\(milestoneHash)"
            }
        }

        public let path = "/Destiny2/Milestones/{milestoneHash}/Content/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
