// This File was auto generated by BungoKitGen
//
// File: InsertSocketPlugFree.swift

import Foundation

public extension Requests.Destiny2 {
    /// Insert a 'free' plug into an item's socket. This does not require 'Advanced Write Action' authorization and is available to 3rd-party apps, but will only work on 'free and reversible' socket actions (Perks, Armor Mods, Shaders, Ornaments, etc.). You must have a valid Destiny Account, and the character must either be in a social space, in orbit, or offline.
    struct InsertSocketPlugFreeRequest: BungoRequest {
        public typealias Response = Destiny.Responses.DestinyItemChangeResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/Destiny2/Actions/Items/InsertSocketPlugFree/"
        public let parameters: Parameters
        public let method: HTTPMethod = .post
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
