// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: SearchDestinyEntities.swift

import Foundation

public extension Requests.Destiny2 {
    /// Gets a page list of Destiny items.
    struct SearchDestinyEntitiesRequest: BungoRequest {
        public typealias Response = Destiny.Definitions.DestinyEntitySearchResult

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(searchTerm: String, type: String, page: Int32? = nil) {
                query = [:]
                path = [:]

                if let page {
                    query["page"] = "\(page)"
                }

                path["searchTerm"] = "\(searchTerm)"
                path["type"] = "\(type)"
            }
        }

        public let path = "/Destiny2/Armory/Search/{type}/{searchTerm}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
