// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyVendorReceiptsComponent.swift

import Foundation

public extension Destiny.Entities.Profiles {
    /// For now, this isn't used for much: it's a record of the recent refundable purchases that the user has made. In the future, it could be used for providing refunds/buyback via the API. Wouldn't that be fun?
    struct DestinyVendorReceiptsComponent: Codable {
        /// The receipts for refundable purchases made at a vendor.
        public var receipts: [Destiny.Vendors.DestinyVendorReceipt]?

        public enum CodingKeys: String, CodingKey {
            case receipts
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            receipts = try? container.decode([Destiny.Vendors.DestinyVendorReceipt].self, forKey: CodingKeys.receipts)
        }
    }
}
