// This File was auto generated by BungoKitGen
//
// File: GetCoreTopicsPaged.swift

import Foundation

public extension Requests.Forum {
    /// Gets a listing of all topics marked as part of the core group.
    struct GetCoreTopicsPagedRequest: BungoRequest {
        public typealias Response = Forum.PostSearchResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(categoryFilter: Forum.ForumTopicsCategoryFiltersEnum, page: Int32, quickDate: Forum.ForumTopicsQuickDateEnum, sort: Forum.ForumTopicsSortEnum, locales: String? = nil) {
                query = [:]
                path = [:]

                if let locales {
                    query["locales"] = "\(locales)"
                }

                path["categoryFilter"] = "\(categoryFilter.rawValue)"
                path["page"] = "\(page)"
                path["quickDate"] = "\(quickDate.rawValue)"
                path["sort"] = "\(sort.rawValue)"
            }
        }

        public let path = "/Forum/GetCoreTopicsPaged/{page}/{sort}/{quickDate}/{categoryFilter}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
