// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetPoll.swift

import Foundation

public extension Requests.Forum {
    /// Gets the specified forum poll.
    struct GetPollRequest: BungoRequest {
        public typealias Response = Forum.PostSearchResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(topicId: Int64) {
                query = [:]
                path = [:]

                path["topicId"] = "\(topicId)"
            }
        }

        public let path = "/Forum/Poll/{topicId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
