// This File was auto generated by BungoKitGen
//
// File: GetTopicsPaged.swift

import Foundation

public extension Requests.Forum {
    /// Get topics from any forum.
    struct GetTopicsPagedRequest: BungoRequest {
        public typealias Response = Forum.PostSearchResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(categoryFilter: Forum.ForumTopicsCategoryFiltersEnum, group: Int64, page: Int32, pageSize: Int32, quickDate: Forum.ForumTopicsQuickDateEnum, sort: Forum.ForumTopicsSortEnum, locales: String? = nil, tagstring: String? = nil) {
                query = [:]
                path = [:]

                if let locales {
                    query["locales"] = "\(locales)"
                }
                if let tagstring {
                    query["tagstring"] = "\(tagstring)"
                }

                path["categoryFilter"] = "\(categoryFilter.rawValue)"
                path["group"] = "\(group)"
                path["page"] = "\(page)"
                path["pageSize"] = "\(pageSize)"
                path["quickDate"] = "\(quickDate.rawValue)"
                path["sort"] = "\(sort.rawValue)"
            }
        }

        public let path = "/Forum/GetTopicsPaged/{page}/{pageSize}/{group}/{sort}/{quickDate}/{categoryFilter}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
