// This File was auto generated by BungieAPIGen
//
// DeveloperRole.swift

import Foundation

public extension Applications {
    enum DeveloperRole: Int32, Codable {
        case none = 0
        case owner = 1
        case teamMember = 2
    }
}
