// This File was auto generated by BungoKitGen
//
// File: DestinyRecordsComponent.swift

import Foundation

public extension Destiny.Components.Records {
    struct DestinyRecordsComponent: Codable {
        /// The hash for the root presentation node definition of Triumph categories.
        public var recordCategoriesRootNodeHash: UInt32?
        /// The hash for the root presentation node definition of Triumph Seals.
        public var recordSealsRootNodeHash: UInt32?
        public var records: [Int: Destiny.Components.Records.DestinyRecordComponent]?

        public enum CodingKeys: String, CodingKey {
            case recordCategoriesRootNodeHash
            case recordSealsRootNodeHash
            case records
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            recordCategoriesRootNodeHash = try? container.decode(UInt32.self, forKey: CodingKeys.recordCategoriesRootNodeHash)
            recordSealsRootNodeHash = try? container.decode(UInt32.self, forKey: CodingKeys.recordSealsRootNodeHash)
            records = try? container.decode([Int: Destiny.Components.Records.DestinyRecordComponent].self, forKey: CodingKeys.records)
        }
    }
}
