// This File was auto generated by BungoKitGen
//
// File: AwaPermissionRequested.swift

import Foundation

public extension Destiny.Advanced {
    struct AwaPermissionRequested: Codable {
        /// Item instance ID the action shall be applied to. This is optional for all but a new AwaType values. Rule of thumb is to provide the item instance ID if one is available.
        public var affectedItemId: Int64?
        /// Destiny character ID, if applicable, that will be affected by the action.
        public var characterId: Int64?
        /// Destiny membership type of the account to modify.
        public var membershipType: BungieMembershipType?
        /// Type of advanced write action.
        public var type: Destiny.Advanced.AwaType?

        public enum CodingKeys: String, CodingKey {
            case affectedItemId
            case characterId
            case membershipType
            case type
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            let affectedItemId = try? container.decode(String.self, forKey: CodingKeys.affectedItemId)
            if let affectedItemId, let affectedItemIdInt = Int64(affectedItemId) {
                self.affectedItemId = affectedItemIdInt
            } else {
                self.affectedItemId = nil
            }
            let characterId = try? container.decode(String.self, forKey: CodingKeys.characterId)
            if let characterId, let characterIdInt = Int64(characterId) {
                self.characterId = characterIdInt
            } else {
                self.characterId = nil
            }
            membershipType = try? container.decode(BungieMembershipType.self, forKey: CodingKeys.membershipType)
            type = try? container.decode(Destiny.Advanced.AwaType.self, forKey: CodingKeys.type)
        }
    }
}
