// This File was auto generated by BungoKitGen
//
// File: AwaUserResponse.swift

import Foundation

public extension Destiny.Advanced {
    struct AwaUserResponse: Codable {
        /// Correlation ID of the request
        public var correlationId: String?
        /// Secret nonce received via the PUSH notification.
        public var nonce: [UInt8]?
        /// Indication of the selection the user has made (Approving or rejecting the action)
        public var selection: Destiny.Advanced.AwaUserSelection?

        public enum CodingKeys: String, CodingKey {
            case correlationId
            case nonce
            case selection
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            correlationId = try? container.decode(String.self, forKey: CodingKeys.correlationId)
            nonce = try? container.decode([UInt8].self, forKey: CodingKeys.nonce)
            selection = try? container.decode(Destiny.Advanced.AwaUserSelection.self, forKey: CodingKeys.selection)
        }
    }
}
