// This File was auto generated by BungieAPIGen
//
// AwaUserSelection.swift

import Foundation

public extension Destiny.Advanced {
    enum AwaUserSelection: Int32, Codable {
        case none = 0
        case rejected = 1
        case approved = 2
    }
}
