// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetTrendingEntryDetail.swift

import Foundation

public extension Requests.Trending {
    /// Returns the detailed results for a specific trending entry. Note that trending entries are uniquely identified by a combination of *both* the TrendingEntryType *and* the identifier: the identifier alone is not guaranteed to be globally unique.
    struct GetTrendingEntryDetailRequest: BungoRequest {
        public typealias Response = Trending.TrendingDetail

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(identifier: String, trendingEntryType: Trending.TrendingEntryType) {
                query = [:]
                path = [:]

                path["identifier"] = "\(identifier)"
                path["trendingEntryType"] = "\(trendingEntryType.rawValue)"
            }
        }

        public let path = "/Trending/Details/{trendingEntryType}/{identifier}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
