// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetCredentialTypesForTargetAccount.swift

import AnyCodable
import Foundation
public extension Requests.User {
    /// Returns a list of credential types attached to the requested account
    struct GetCredentialTypesForTargetAccountRequest: BungoRequest {
        public typealias Response = AnyCodable

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(membershipId: Int64) {
                query = [:]
                path = [:]

                path["membershipId"] = "\(membershipId)"
            }
        }

        public let path = "/User/GetCredentialTypesForTargetAccount/{membershipId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
