// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetSanitizedPlatformDisplayNames.swift

import AnyCodable
import Foundation
public extension Requests.User {
    /// Gets a list of all display names linked to this membership id but sanitized (profanity filtered). Obeys all visibility rules of calling user and is heavily cached.
    struct GetSanitizedPlatformDisplayNamesRequest: BungoRequest {
        public typealias Response = AnyCodable

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(membershipId: Int64) {
                query = [:]
                path = [:]

                path["membershipId"] = "\(membershipId)"
            }
        }

        public let path = "/User/GetSanitizedPlatformDisplayNames/{membershipId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
