// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: SearchByGlobalNamePost.swift

import Foundation

public extension Requests.User {
    /// Given the prefix of a global display name, returns all users who share that name.
    struct SearchByGlobalNamePostRequest: BungoRequest {
        public typealias Response = User.UserSearchResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(page: Int32) {
                query = [:]
                path = [:]

                path["page"] = "\(page)"
            }
        }

        public let path = "/User/Search/GlobalName/{page}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .post
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
