// This File was auto generated by BungoKitGen
//
// File: ContentTypeDefaultValue.swift

import Foundation

public extension Content.Models {
    struct ContentTypeDefaultValue: Codable {
        public var defaultValue: String?
        public var whenClause: String?
        public var whenValue: String?

        public enum CodingKeys: String, CodingKey {
            case defaultValue
            case whenClause
            case whenValue
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            defaultValue = try? container.decode(String.self, forKey: CodingKeys.defaultValue)
            whenClause = try? container.decode(String.self, forKey: CodingKeys.whenClause)
            whenValue = try? container.decode(String.self, forKey: CodingKeys.whenValue)
        }
    }
}
