// This File was auto generated by BungoKitGen
//
// File: TagMetadataItem.swift

import Foundation

public extension Content.Models {
    struct TagMetadataItem: Codable {
        public var description: String?
        public var groups: [String]?
        public var isDefault: Bool?
        public var name: String?
        public var tagText: String?

        public enum CodingKeys: String, CodingKey {
            case description
            case groups
            case isDefault
            case name
            case tagText
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            description = try? container.decode(String.self, forKey: CodingKeys.description)
            groups = try? container.decode([String].self, forKey: CodingKeys.groups)
            isDefault = try? container.decode(Bool.self, forKey: CodingKeys.isDefault)
            name = try? container.decode(String.self, forKey: CodingKeys.name)
            tagText = try? container.decode(String.self, forKey: CodingKeys.tagText)
        }
    }
}
