// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: Capabilities.swift

import Foundation

public extension GroupsV2 {
    enum Capabilities: Int32, Codable {
        case none = 0
        case leaderboards = 1
        case callsign = 2
        case optionalConversations = 4
        case clanBanner = 8
        case d2InvestmentData = 16
        case tags = 32
        case alliances = 64
    }
}
