// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GroupMember.swift

import Foundation

public extension GroupsV2 {
    struct GroupMember: Codable {
        public var bungieNetUserInfo: User.UserInfoCard?

        public var destinyUserInfo: GroupsV2.GroupUserInfoCard?

        public var groupId: Int64?

        public var isOnline: Bool?

        public var joinDate: Date?

        public var lastOnlineStatusChange: Int64?

        public var memberType: GroupsV2.RuntimeGroupMemberType?

        public enum CodingKeys: String, CodingKey {
            case bungieNetUserInfo
            case destinyUserInfo
            case groupId
            case isOnline
            case joinDate
            case lastOnlineStatusChange
            case memberType
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            bungieNetUserInfo = try? container.decode(User.UserInfoCard.self, forKey: CodingKeys.bungieNetUserInfo)
            destinyUserInfo = try? container.decode(GroupsV2.GroupUserInfoCard.self, forKey: CodingKeys.destinyUserInfo)
            let groupId = try? container.decode(String.self, forKey: CodingKeys.groupId)
            if let groupId, let groupIdInt = Int64(groupId) {
                self.groupId = groupIdInt
            } else {
                self.groupId = nil
            }
            isOnline = try? container.decode(Bool.self, forKey: CodingKeys.isOnline)
            joinDate = try? container.decode(Date.self, forKey: CodingKeys.joinDate)
            let lastOnlineStatusChange = try? container.decode(String.self, forKey: CodingKeys.lastOnlineStatusChange)
            if let lastOnlineStatusChange, let lastOnlineStatusChangeInt = Int64(lastOnlineStatusChange) {
                self.lastOnlineStatusChange = lastOnlineStatusChangeInt
            } else {
                self.lastOnlineStatusChange = nil
            }
            memberType = try? container.decode(GroupsV2.RuntimeGroupMemberType.self, forKey: CodingKeys.memberType)
        }
    }
}
