// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GroupSortBy.swift

import Foundation

public extension GroupsV2 {
    enum GroupSortBy: Int32, Codable {
        case name = 0
        case date = 1
        case popularity = 2
        case id = 3
    }
}
