// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GroupType.swift

import Foundation

public extension GroupsV2 {
    enum GroupType: Int32, Codable {
        case general = 0
        case clan = 1
    }
}
