// This File was auto generated by BungoKitGen
//
// File: GroupOptionalConversationAddRequest.swift

import Foundation

public extension GroupsV2 {
    struct GroupOptionalConversationAddRequest: Codable {
        public var chatName: String?
        public var chatSecurity: GroupsV2.ChatSecuritySetting?

        public enum CodingKeys: String, CodingKey {
            case chatName
            case chatSecurity
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            chatName = try? container.decode(String.self, forKey: CodingKeys.chatName)
            chatSecurity = try? container.decode(GroupsV2.ChatSecuritySetting.self, forKey: CodingKeys.chatSecurity)
        }
    }
}
