// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GroupsForMemberFilter.swift

import Foundation

public extension GroupsV2 {
    enum GroupsForMemberFilter: Int32, Codable {
        case all = 0
        case founded = 1
        case nonFounded = 2
    }
}
