// This File was auto generated by BungieAPIGen
//
// MembershipOption.swift

import Foundation

public extension GroupsV2 {
    enum MembershipOption: Int32, Codable {
        case reviewed = 0
        case open = 1
        case closed = 2
    }
}
