// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyProfileTransitoryPartyMember.swift

import Foundation

public extension Destiny.Components.Profiles {
    /// This is some bare minimum information about a party member in a Fireteam. Unfortunately, without great computational expense on our side we can only get at the data contained here. I'd like to give you a character ID for example, but we don't have it. But we do have these three pieces of information. May they help you on your quest to show meaningful data about current Fireteams.
    /// Notably, we don't and can't feasibly return info on characters. If you can, try to use just the data below for your UI and purposes. Only hit us with further queries if you absolutely must know the character ID of the currently playing character. Pretty please with sugar on top.
    struct DestinyProfileTransitoryPartyMember: Codable {
        /// The player's last known display name.
        public var displayName: String?

        /// The identifier for the DestinyInventoryItemDefinition of the player's emblem.
        public var emblemHash: UInt32?

        /// The Membership ID that matches the party member.
        public var membershipId: Int64?

        /// A Flags Enumeration value indicating the states that the player is in relevant to being on a fireteam.
        public var status: Destiny.DestinyPartyMemberStates?

        public enum CodingKeys: String, CodingKey {
            case displayName
            case emblemHash
            case membershipId
            case status
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            displayName = try? container.decode(String.self, forKey: CodingKeys.displayName)
            emblemHash = try? container.decode(UInt32.self, forKey: CodingKeys.emblemHash)
            let membershipId = try? container.decode(String.self, forKey: CodingKeys.membershipId)
            if let membershipId, let membershipIdInt = Int64(membershipId) {
                self.membershipId = membershipIdInt
            } else {
                self.membershipId = nil
            }
            status = try? container.decode(Destiny.DestinyPartyMemberStates.self, forKey: CodingKeys.status)
        }
    }
}
