// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyCharacterActionRequest.swift

import Foundation

public extension Destiny.Requests.Actions {
    struct DestinyCharacterActionRequest: Codable {
        public var characterId: Int64?

        public var membershipType: BungieMembershipType?

        public enum CodingKeys: String, CodingKey {
            case characterId
            case membershipType
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            let characterId = try? container.decode(String.self, forKey: CodingKeys.characterId)
            if let characterId, let characterIdInt = Int64(characterId) {
                self.characterId = characterIdInt
            } else {
                self.characterId = nil
            }
            membershipType = try? container.decode(BungieMembershipType.self, forKey: CodingKeys.membershipType)
        }
    }
}
