// This File was auto generated by BungoKitGen
//
// File: DestinyMilestoneQuest.swift

import Foundation

public extension Destiny.Milestones {
    /// If a Milestone has one or more Quests, this will contain the live information for the character's status with one of those quests.
    struct DestinyMilestoneQuest: Codable {
        /// *IF* the Milestone has an active Activity that can give you greater details about what you need to do, it will be returned here. Remember to associate this with the DestinyMilestoneDefinition's activities to get details about the activity, including what specific quest it is related to if you have multiple quests to choose from.
        public var activity: Destiny.Milestones.DestinyMilestoneActivity?
        /// The activities referred to by this quest can have many associated challenges. They are all contained here, with activityHashes so that you can associate them with the specific activity variants in which they can be found. In retrospect, I probably should have put these under the specific Activity Variants, but it's too late to change it now. Theoretically, a quest without Activities can still have Challenges, which is why this is on a higher level than activity/variants, but it probably should have been in both places. That may come as a later revision.
        public var challenges: [Destiny.Challenges.DestinyChallengeStatus]?
        /// Quests are defined as Items in content. As such, this is the hash identifier of the DestinyInventoryItemDefinition that represents this quest. It will have pointers to all of the steps in the quest, and display information for the quest (title, description, icon etc) Individual steps will be referred to in the Quest item's DestinyInventoryItemDefinition.setData property, and themselves are Items with their own renderable data.
        public var questItemHash: UInt32?
        /// The current status of the quest for the character making the request.
        public var status: Destiny.Quests.DestinyQuestStatus?

        public enum CodingKeys: String, CodingKey {
            case activity
            case challenges
            case questItemHash
            case status
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            activity = try? container.decode(Destiny.Milestones.DestinyMilestoneActivity.self, forKey: CodingKeys.activity)
            challenges = try? container.decode([Destiny.Challenges.DestinyChallengeStatus].self, forKey: CodingKeys.challenges)
            questItemHash = try? container.decode(UInt32.self, forKey: CodingKeys.questItemHash)
            status = try? container.decode(Destiny.Quests.DestinyQuestStatus.self, forKey: CodingKeys.status)
        }
    }
}
