// This File was auto generated by BungoKitGen
//
// File: GetGroupOptionalConversations.swift

import AnyCodable
import Foundation
public extension Requests.GroupV2 {
    /// Gets a list of available optional conversation channels and their settings.
    struct GetGroupOptionalConversationsRequest: BungoRequest {
        public typealias Response = AnyCodable

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(groupId: Int64) {
                query = [:]
                path = [:]

                path["groupId"] = "\(groupId)"
            }
        }

        public let path = "/GroupV2/{groupId}/OptionalConversations/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
