// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GroupSearch.swift

import Foundation

public extension Requests.GroupV2 {
    /// Search for Groups.
    struct GroupSearchRequest: BungoRequest {
        public typealias Response = GroupsV2.GroupSearchResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init() {
                query = [:]
                path = [:]
            }
        }

        public let path = "/GroupV2/Search/"
        public let parameters: Parameters
        public let method: HTTPMethod = .post
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
