// This File was auto generated by BungoKitGen
//
// File: IndividualGroupInvite.swift

import Foundation

public extension Requests.GroupV2 {
    /// Invite a user to join this group.
    struct IndividualGroupInviteRequest: BungoRequest {
        public typealias Response = GroupsV2.GroupApplicationResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(groupId: Int64, membershipId: Int64, membershipType: BungieMembershipType) {
                query = [:]
                path = [:]

                path["groupId"] = "\(groupId)"
                path["membershipId"] = "\(membershipId)"
                path["membershipType"] = "\(membershipType.rawValue)"
            }
        }

        public let path = "/GroupV2/{groupId}/Members/IndividualInvite/{membershipType}/{membershipId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .post
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
