// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetBungieRewardsForUser.swift

import AnyCodable
import Foundation
public extension Requests.Tokens {
    /// Returns the bungie rewards for the targeted user.
    struct GetBungieRewardsForUserRequest: BungoRequest {
        public typealias Response = AnyCodable

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(membershipId: Int64) {
                query = [:]
                path = [:]

                path["membershipId"] = "\(membershipId)"
            }
        }

        public let path = "/Tokens/Rewards/GetRewardsForUser/{membershipId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
