// This File was auto generated by BungoKitGen
//
// File: DestinyIconSequenceDefinition.swift

import Foundation

public extension Destiny.Definitions.Common {
    struct DestinyIconSequenceDefinition: Codable {
        public var frames: [String]?

        public enum CodingKeys: String, CodingKey {
            case frames
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            frames = try? container.decode([String].self, forKey: CodingKeys.frames)
        }
    }
}
