// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyCollectiblesComponent.swift

import Foundation

public extension Destiny.Components.Collectibles {
    struct DestinyCollectiblesComponent: Codable {
        public var collectibles: [UInt32: Destiny.Components.Collectibles.DestinyCollectibleComponent]?

        /// The hash for the root presentation node definition of Collection Badges.
        public var collectionBadgesRootNodeHash: UInt32?

        /// The hash for the root presentation node definition of Collection categories.
        public var collectionCategoriesRootNodeHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case collectibles
            case collectionBadgesRootNodeHash
            case collectionCategoriesRootNodeHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            let rawcollectibles = try? container.decode([String: Destiny.Components.Collectibles.DestinyCollectibleComponent].self, forKey: CodingKeys.collectibles)
            collectibles = rawcollectibles?.compactMapKeys { key, _ -> UInt32? in
                UInt32(key)
            }
            collectionBadgesRootNodeHash = try? container.decode(UInt32.self, forKey: CodingKeys.collectionBadgesRootNodeHash)
            collectionCategoriesRootNodeHash = try? container.decode(UInt32.self, forKey: CodingKeys.collectionCategoriesRootNodeHash)
        }
    }
}
