// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: TrendingEntryDestinyRitual.swift

import Foundation

public extension Trending {
    struct TrendingEntryDestinyRitual: Codable {
        public var dateEnd: Date?

        public var dateStart: Date?

        /// A destiny event will not necessarily have milestone "custom content", but if it does the details will be here.
        public var eventContent: Destiny.Milestones.DestinyMilestoneContent?

        public var icon: String?

        public var image: String?

        /// A destiny event does not necessarily have a related Milestone, but if it does the details will be returned here.
        public var milestoneDetails: Destiny.Milestones.DestinyPublicMilestone?

        public var subtitle: String?

        public var title: String?

        public enum CodingKeys: String, CodingKey {
            case dateEnd
            case dateStart
            case eventContent
            case icon
            case image
            case milestoneDetails
            case subtitle
            case title
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            dateEnd = try? container.decode(Date.self, forKey: CodingKeys.dateEnd)
            dateStart = try? container.decode(Date.self, forKey: CodingKeys.dateStart)
            eventContent = try? container.decode(Destiny.Milestones.DestinyMilestoneContent.self, forKey: CodingKeys.eventContent)
            icon = try? container.decode(String.self, forKey: CodingKeys.icon)
            image = try? container.decode(String.self, forKey: CodingKeys.image)
            milestoneDetails = try? container.decode(Destiny.Milestones.DestinyPublicMilestone.self, forKey: CodingKeys.milestoneDetails)
            subtitle = try? container.decode(String.self, forKey: CodingKeys.subtitle)
            title = try? container.decode(String.self, forKey: CodingKeys.title)
        }
    }
}
