// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: TrendingEntryNews.swift

import Foundation

public extension Trending {
    struct TrendingEntryNews: Codable {
        public var article: Content.ContentItemPublicContract?

        public enum CodingKeys: String, CodingKey {
            case article
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            article = try? container.decode(Content.ContentItemPublicContract.self, forKey: CodingKeys.article)
        }
    }
}
