// This File was auto generated by BungoKitGen
//
// File: ComponentResponse.swift

import Foundation

public extension Components {
    /// The base class for any component-returning object that may need to indicate information about the state of the component being returned.
    struct ComponentResponse: Codable {
        /// If true, this component is disabled.
        public var disabled: Bool?
        public var privacy: Components.ComponentPrivacySetting?

        public enum CodingKeys: String, CodingKey {
            case disabled
            case privacy
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            disabled = try? container.decode(Bool.self, forKey: CodingKeys.disabled)
            privacy = try? container.decode(Components.ComponentPrivacySetting.self, forKey: CodingKeys.privacy)
        }
    }
}
