// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: ContentRepresentation.swift

import Foundation

public extension Content {
    struct ContentRepresentation: Codable {
        public var name: String?

        public var path: String?

        public var validationString: String?

        public enum CodingKeys: String, CodingKey {
            case name
            case path
            case validationString
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            name = try? container.decode(String.self, forKey: CodingKeys.name)
            path = try? container.decode(String.self, forKey: CodingKeys.path)
            validationString = try? container.decode(String.self, forKey: CodingKeys.validationString)
        }
    }
}
