// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: NewsArticleRssItem.swift

import Foundation

public extension Content {
    struct NewsArticleRssItem: Codable {
        public var description: String?

        public var htmlContent: String?

        public var imagePath: String?

        public var link: String?

        public var optionalMobileImagePath: String?

        public var pubDate: Date?

        public var title: String?

        public var uniqueIdentifier: String?

        public enum CodingKeys: String, CodingKey {
            case description = "Description"
            case htmlContent = "HtmlContent"
            case imagePath = "ImagePath"
            case link = "Link"
            case optionalMobileImagePath = "OptionalMobileImagePath"
            case pubDate = "PubDate"
            case title = "Title"
            case uniqueIdentifier = "UniqueIdentifier"
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            description = try? container.decode(String.self, forKey: CodingKeys.description)
            htmlContent = try? container.decode(String.self, forKey: CodingKeys.htmlContent)
            imagePath = try? container.decode(String.self, forKey: CodingKeys.imagePath)
            link = try? container.decode(String.self, forKey: CodingKeys.link)
            optionalMobileImagePath = try? container.decode(String.self, forKey: CodingKeys.optionalMobileImagePath)
            pubDate = try? container.decode(Date.self, forKey: CodingKeys.pubDate)
            title = try? container.decode(String.self, forKey: CodingKeys.title)
            uniqueIdentifier = try? container.decode(String.self, forKey: CodingKeys.uniqueIdentifier)
        }
    }
}
