// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyActivityModifierDefinition.swift

import Foundation

public extension Destiny.Definitions.ActivityModifiers {
    /// Modifiers - in Destiny 1, these were referred to as "Skulls" - are changes that can be applied to an Activity.
    struct DestinyActivityModifierDefinition: Codable {
        public var displayInActivitySelection: Bool?

        public var displayInNavMode: Bool?

        public var displayProperties: Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition?

        /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
        /// When entities refer to each other in Destiny content, it is this hash that they are referring to.
        public var hash: UInt32?

        /// The index of the entity as it was found in the investment tables.
        public var index: Int32?

        /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
        public var redacted: Bool?

        public enum CodingKeys: String, CodingKey {
            case displayInActivitySelection
            case displayInNavMode
            case displayProperties
            case hash
            case index
            case redacted
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            displayInActivitySelection = try? container.decode(Bool.self, forKey: CodingKeys.displayInActivitySelection)
            displayInNavMode = try? container.decode(Bool.self, forKey: CodingKeys.displayInNavMode)
            displayProperties = try? container.decode(Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition.self, forKey: CodingKeys.displayProperties)
            hash = try? container.decode(UInt32.self, forKey: CodingKeys.hash)
            index = try? container.decode(Int32.self, forKey: CodingKeys.index)
            redacted = try? container.decode(Bool.self, forKey: CodingKeys.redacted)
        }
    }
}
