// This File was auto generated by BungoKitGen
//
// File: DestinyItemSetBlockEntryDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// Defines a particular entry in an ItemSet (AKA a particular Quest Step in a Quest)
    struct DestinyItemSetBlockEntryDefinition: Codable {
        /// This is the hash identifier for a DestinyInventoryItemDefinition representing this quest step.
        public var itemHash: UInt32?
        /// Used for tracking which step a user reached. These values will be populated in the user's internal state, which we expose externally as a more usable DestinyQuestStatus object. If this item has been obtained, this value will be set in trackingUnlockValueHash.
        public var trackingValue: Int32?

        public enum CodingKeys: String, CodingKey {
            case itemHash
            case trackingValue
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            itemHash = try? container.decode(UInt32.self, forKey: CodingKeys.itemHash)
            trackingValue = try? container.decode(Int32.self, forKey: CodingKeys.trackingValue)
        }
    }
}
