// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyActivityLoadoutRequirement.swift

import Foundation

public extension Destiny.Definitions {
    struct DestinyActivityLoadoutRequirement: Codable {
        public var allowedEquippedItemHashes: [UInt32]?

        public var allowedWeaponSubTypes: [Destiny.DestinyItemSubType]?

        public var equipmentSlotHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case allowedEquippedItemHashes
            case allowedWeaponSubTypes
            case equipmentSlotHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            allowedEquippedItemHashes = try? container.decode([UInt32].self, forKey: CodingKeys.allowedEquippedItemHashes)
            allowedWeaponSubTypes = try? container.decode([Destiny.DestinyItemSubType].self, forKey: CodingKeys.allowedWeaponSubTypes)
            equipmentSlotHash = try? container.decode(UInt32.self, forKey: CodingKeys.equipmentSlotHash)
        }
    }
}
