// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyItemPreviewBlockDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// Items like Sacks or Boxes can have items that it shows in-game when you view details that represent the items you can obtain if you use or acquire the item.
    /// This defines those categories, and gives some insights into that data's source.
    struct DestinyItemPreviewBlockDefinition: Codable {
        /// If this item should show you Artifact information when you preview it, this is the hash identifier of the DestinyArtifactDefinition for the artifact whose data should be shown.
        public var artifactHash: UInt32?

        /// This is a list of the items being previewed, categorized in the same way as they are in the preview UI.
        public var derivedItemCategories: [Destiny.Definitions.Items.DestinyDerivedItemCategoryDefinition]?

        /// If the preview has an associated action (like "Open"), this will be the localized string for that action.
        public var previewActionString: String?

        /// If the preview data is derived from a fake "Preview" Vendor, this will be the hash identifier for the DestinyVendorDefinition of that fake vendor.
        public var previewVendorHash: UInt32?

        /// A string that the game UI uses as a hint for which detail screen to show for the item. You, too, can leverage this for your own custom screen detail views. Note, however, that these are arbitrarily defined by designers: there's no guarantees of a fixed, known number of these - so fall back to something reasonable if you don't recognize it.
        public var screenStyle: String?

        public enum CodingKeys: String, CodingKey {
            case artifactHash
            case derivedItemCategories
            case previewActionString
            case previewVendorHash
            case screenStyle
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            artifactHash = try? container.decode(UInt32.self, forKey: CodingKeys.artifactHash)
            derivedItemCategories = try? container.decode([Destiny.Definitions.Items.DestinyDerivedItemCategoryDefinition].self, forKey: CodingKeys.derivedItemCategories)
            previewActionString = try? container.decode(String.self, forKey: CodingKeys.previewActionString)
            previewVendorHash = try? container.decode(UInt32.self, forKey: CodingKeys.previewVendorHash)
            screenStyle = try? container.decode(String.self, forKey: CodingKeys.screenStyle)
        }
    }
}
