// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyPlugItemCraftingRequirements.swift

import Foundation

public extension Destiny.Definitions {
    struct DestinyPlugItemCraftingRequirements: Codable {
        public var materialRequirementHashes: [UInt32]?

        /// If the plug has a known level requirement, it'll be available here.
        public var requiredLevel: Int32?

        public var unlockRequirements: [Destiny.Definitions.DestinyPlugItemCraftingUnlockRequirement]?

        public enum CodingKeys: String, CodingKey {
            case materialRequirementHashes
            case requiredLevel
            case unlockRequirements
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            materialRequirementHashes = try? container.decode([UInt32].self, forKey: CodingKeys.materialRequirementHashes)
            requiredLevel = try? container.decode(Int32.self, forKey: CodingKeys.requiredLevel)
            unlockRequirements = try? container.decode([Destiny.Definitions.DestinyPlugItemCraftingUnlockRequirement].self, forKey: CodingKeys.unlockRequirements)
        }
    }
}
