// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyVendorRequirementDisplayEntryDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// The localized properties of the requirementsDisplay, allowing information about the requirement or item being featured to be seen.
    struct DestinyVendorRequirementDisplayEntryDefinition: Codable {
        public var icon: String?

        public var name: String?

        public var source: String?

        public var type: String?

        public enum CodingKeys: String, CodingKey {
            case icon
            case name
            case source
            case type
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            icon = try? container.decode(String.self, forKey: CodingKeys.icon)
            name = try? container.decode(String.self, forKey: CodingKeys.name)
            source = try? container.decode(String.self, forKey: CodingKeys.source)
            type = try? container.decode(String.self, forKey: CodingKeys.type)
        }
    }
}
