// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyGearArtArrangementReference.swift

import Foundation

public extension Destiny.Definitions {
    struct DestinyGearArtArrangementReference: Codable {
        public var artArrangementHash: UInt32?

        public var classHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case artArrangementHash
            case classHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            artArrangementHash = try? container.decode(UInt32.self, forKey: CodingKeys.artArrangementHash)
            classHash = try? container.decode(UInt32.self, forKey: CodingKeys.classHash)
        }
    }
}
