// This File was auto generated by BungieAPIGen
//
// DestinyTalentNodeStepLightAbilities.swift

import Foundation

public extension Destiny.Definitions {
    enum DestinyTalentNodeStepLightAbilities: Int32, Codable {
        case none = 0
        case grenades = 1
        case melee = 2
        case movementModes = 4
        case orbs = 8
        case superEnergy = 16
        case superMods = 32
        case all = 63
    }
}
