// This File was auto generated by BungoKitGen
//
// File: DestinyItemTalentGridBlockDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// This defines information that can only come from a talent grid on an item. Items mostly have negligible talent grid data these days, but instanced items still retain grids as a source for some of this common information.
    /// Builds/Subclasses are the only items left that still have talent grids with meaningful Nodes.
    struct DestinyItemTalentGridBlockDefinition: Codable {
        /// A shortcut string identifier for the "build" in question, if this talent grid has an associated build. Doesn't map to anything we can expose at the moment.
        public var buildName: String?
        /// If the talent grid implies a damage type, this is the enum value for that damage type.
        public var hudDamageType: Destiny.DamageType?
        /// If the talent grid has a special icon that's shown in the game UI (like builds, funny that), this is the identifier for that icon. Sadly, we don't actually get that icon right now. I'll be looking to replace this with a path to the actual icon itself.
        public var hudIcon: String?
        /// This is meant to be a subtitle for looking at the talent grid. In practice, somewhat frustratingly, this always merely says the localized word for "Details". Great. Maybe it'll have more if talent grids ever get used for more than builds and subclasses again.
        public var itemDetailString: String?
        /// The hash identifier of the DestinyTalentGridDefinition attached to this item.
        public var talentGridHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case buildName
            case hudDamageType
            case hudIcon
            case itemDetailString
            case talentGridHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            buildName = try? container.decode(String.self, forKey: CodingKeys.buildName)
            hudDamageType = try? container.decode(Destiny.DamageType.self, forKey: CodingKeys.hudDamageType)
            hudIcon = try? container.decode(String.self, forKey: CodingKeys.hudIcon)
            itemDetailString = try? container.decode(String.self, forKey: CodingKeys.itemDetailString)
            talentGridHash = try? container.decode(UInt32.self, forKey: CodingKeys.talentGridHash)
        }
    }
}
