// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyVendorInteractionReplyDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// When the interaction is replied to, Reward sites will fire and items potentially selected based on whether the given unlock expression is TRUE.
    /// You can potentially choose one from multiple replies when replying to an interaction: this is how you get either/or rewards from vendors.
    struct DestinyVendorInteractionReplyDefinition: Codable {
        /// The rewards granted upon responding to the vendor.
        public var itemRewardsSelection: Destiny.DestinyVendorInteractionRewardSelection?

        /// The localized text for the reply.
        public var reply: String?

        /// An enum indicating the type of reply being made.
        public var replyType: Destiny.DestinyVendorReplyType?

        public enum CodingKeys: String, CodingKey {
            case itemRewardsSelection
            case reply
            case replyType
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            itemRewardsSelection = try? container.decode(Destiny.DestinyVendorInteractionRewardSelection.self, forKey: CodingKeys.itemRewardsSelection)
            reply = try? container.decode(String.self, forKey: CodingKeys.reply)
            replyType = try? container.decode(Destiny.DestinyVendorReplyType.self, forKey: CodingKeys.replyType)
        }
    }
}
