// This File was auto generated by BungoKitGen
//
// File: DestinyActivityGraphListEntryDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// Destinations and Activities may have default Activity Graphs that should be shown when you bring up the Director and are playing in either.
    /// This contract defines the graph referred to and the gating for when it is relevant.
    struct DestinyActivityGraphListEntryDefinition: Codable {
        /// The hash identifier of the DestinyActivityGraphDefinition that should be shown when opening the director.
        public var activityGraphHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case activityGraphHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            activityGraphHash = try? container.decode(UInt32.self, forKey: CodingKeys.activityGraphHash)
        }
    }
}
