// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyActivityChallengeDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// Represents a reference to a Challenge, which for now is just an Objective.
    struct DestinyActivityChallengeDefinition: Codable {
        /// The rewards as they're represented in the UI. Note that they generally link to "dummy" items that give a summary of rewards rather than direct, real items themselves.
        /// If the quantity is 0, don't show the quantity.
        public var dummyRewards: [Destiny.DestinyItemQuantity]?

        /// The hash for the Objective that matches this challenge. Use it to look up the DestinyObjectiveDefinition.
        public var objectiveHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case dummyRewards
            case objectiveHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            dummyRewards = try? container.decode([Destiny.DestinyItemQuantity].self, forKey: CodingKeys.dummyRewards)
            objectiveHash = try? container.decode(UInt32.self, forKey: CodingKeys.objectiveHash)
        }
    }
}
