// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyDestinationBubbleSettingDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// Human readable data about the bubble. Combine with DestinyBubbleDefinition - see DestinyDestinationDefinition.bubbleSettings for more information.
    /// DEPRECATED - Just use bubbles.
    struct DestinyDestinationBubbleSettingDefinition: Codable {
        public var displayProperties: Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition?

        public enum CodingKeys: String, CodingKey {
            case displayProperties
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            displayProperties = try? container.decode(Destiny.Definitions.Common.DestinyDisplayPropertiesDefinition.self, forKey: CodingKeys.displayProperties)
        }
    }
}
