// This File was auto generated by BungieAPIGen
//
// DestinyTalentNodeStepDamageTypes.swift

import Foundation

public extension Destiny.Definitions {
    enum DestinyTalentNodeStepDamageTypes: Int32, Codable {
        case none = 0
        case kinetic = 1
        case arc = 2
        case solar = 4
        case void = 8
        case all = 15
    }
}
