// This File was auto generated by BungoKitGen
//
// File: DestinyItemPerkEntryDefinition.swift

import Foundation

public extension Destiny.Definitions {
    /// An intrinsic perk on an item, and the requirements for it to be activated.
    struct DestinyItemPerkEntryDefinition: Codable {
        /// A hash identifier for the DestinySandboxPerkDefinition being provided on the item.
        public var perkHash: UInt32?
        /// Indicates whether this perk should be shown, or if it should be shown disabled.
        public var perkVisibility: Destiny.ItemPerkVisibility?
        /// If this perk is not active, this is the string to show for why it's not providing its benefits.
        public var requirementDisplayString: String?

        public enum CodingKeys: String, CodingKey {
            case perkHash
            case perkVisibility
            case requirementDisplayString
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            perkHash = try? container.decode(UInt32.self, forKey: CodingKeys.perkHash)
            perkVisibility = try? container.decode(Destiny.ItemPerkVisibility.self, forKey: CodingKeys.perkVisibility)
            requirementDisplayString = try? container.decode(String.self, forKey: CodingKeys.requirementDisplayString)
        }
    }
}
