// This File was auto generated by BungoKitGen
//
// File: DestinyArtifactTier.swift

import Foundation

public extension Destiny.Artifacts {
    struct DestinyArtifactTier: Codable {
        public var isUnlocked: Bool?
        public var items: [Destiny.Artifacts.DestinyArtifactTierItem]?
        public var pointsToUnlock: Int32?
        public var tierHash: UInt32?

        public enum CodingKeys: String, CodingKey {
            case isUnlocked
            case items
            case pointsToUnlock
            case tierHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            isUnlocked = try? container.decode(Bool.self, forKey: CodingKeys.isUnlocked)
            items = try? container.decode([Destiny.Artifacts.DestinyArtifactTierItem].self, forKey: CodingKeys.items)
            pointsToUnlock = try? container.decode(Int32.self, forKey: CodingKeys.pointsToUnlock)
            tierHash = try? container.decode(UInt32.self, forKey: CodingKeys.tierHash)
        }
    }
}
