// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyStringVariablesComponent.swift

import Foundation

public extension Destiny.Components.StringVariables {
    struct DestinyStringVariablesComponent: Codable {
        public var integerValuesByHash: [Int: Int32]?

        public enum CodingKeys: String, CodingKey {
            case integerValuesByHash
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            integerValuesByHash = try? container.decode([Int: Int32].self, forKey: CodingKeys.integerValuesByHash)
        }
    }
}
