// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: PagedQuery.swift

import Foundation

public extension Queries {
    struct PagedQuery: Codable {
        public var currentPage: Int32?

        public var itemsPerPage: Int32?

        public var requestContinuationToken: String?

        public enum CodingKeys: String, CodingKey {
            case currentPage
            case itemsPerPage
            case requestContinuationToken
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            currentPage = try? container.decode(Int32.self, forKey: CodingKeys.currentPage)
            itemsPerPage = try? container.decode(Int32.self, forKey: CodingKeys.itemsPerPage)
            requestContinuationToken = try? container.decode(String.self, forKey: CodingKeys.requestContinuationToken)
        }
    }
}
