// This File was auto generated by BungoKitGen
//
// File: DestinyCharacterProgressionComponent.swift

import Foundation

public extension Destiny.Entities.Characters {
    /// This component returns anything that could be considered "Progression" on a user: data where the user is gaining levels, reputation, completions, rewards, etc...
    struct DestinyCharacterProgressionComponent: Codable {
        /// The set of checklists that can be examined for this specific character, keyed by the hash identifier of the Checklist (DestinyChecklistDefinition)
        /// For each checklist returned, its value is itself a Dictionary keyed by the checklist's hash identifier with the value being a boolean indicating if it's been discovered yet.
        public var checklists: [Int: [Int: Bool]]?
        /// A dictionary of all known Factions, keyed by the Faction's hash. It contains data about this character's status with the faction.
        public var factions: [Int: Destiny.Progression.DestinyFactionProgression]?
        /// Milestones are related to the simple progressions shown in the game, but return additional and hopefully helpful information for users about the specifics of the Milestone's status.
        public var milestones: [Int: Destiny.Milestones.DestinyMilestone]?
        /// A Dictionary of all known progressions for the Character, keyed by the Progression's hash.
        /// Not all progressions have user-facing data, but those who do will have that data contained in the DestinyProgressionDefinition.
        public var progressions: [Int: Destiny.DestinyProgression]?
        /// If the user has any active quests, the quests' statuses will be returned here.
        ///  Note that quests have been largely supplanted by Milestones, but that doesn't mean that they won't make a comeback independent of milestones at some point.
        ///  (Fun fact: quests came back as I feared they would, but we never looped back to populate this... I'm going to put that in the backlog.)
        public var quests: [Destiny.Quests.DestinyQuestStatus]?
        /// Data related to your progress on the current season's artifact that can vary per character.
        public var seasonalArtifact: Destiny.Artifacts.DestinyArtifactCharacterScoped?
        /// Sometimes, you have items in your inventory that don't have instances, but still have Objective information. This provides you that objective information for uninstanced items.
        /// This dictionary is keyed by the item's hash: which you can use to look up the name and description for the overall task(s) implied by the objective. The value is the list of objectives for this item, and their statuses.
        public var uninstancedItemObjectives: [Int: [Destiny.Quests.DestinyObjectiveProgress]]?
        /// Sometimes, you have items in your inventory that don't have instances, but still have perks (for example: Trials passage cards). This gives you the perk information for uninstanced items.
        /// This dictionary is keyed by item hash, which you can use to look up the corresponding item definition. The value is the list of perks states for the item.
        public var uninstancedItemPerks: [Int: Destiny.Entities.Items.DestinyItemPerksComponent]?

        public enum CodingKeys: String, CodingKey {
            case checklists
            case factions
            case milestones
            case progressions
            case quests
            case seasonalArtifact
            case uninstancedItemObjectives
            case uninstancedItemPerks
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            checklists = try? container.decode([Int: [Int: Bool]].self, forKey: CodingKeys.checklists)
            factions = try? container.decode([Int: Destiny.Progression.DestinyFactionProgression].self, forKey: CodingKeys.factions)
            milestones = try? container.decode([Int: Destiny.Milestones.DestinyMilestone].self, forKey: CodingKeys.milestones)
            progressions = try? container.decode([Int: Destiny.DestinyProgression].self, forKey: CodingKeys.progressions)
            quests = try? container.decode([Destiny.Quests.DestinyQuestStatus].self, forKey: CodingKeys.quests)
            seasonalArtifact = try? container.decode(Destiny.Artifacts.DestinyArtifactCharacterScoped.self, forKey: CodingKeys.seasonalArtifact)
            uninstancedItemObjectives = try? container.decode([Int: [Destiny.Quests.DestinyObjectiveProgress]].self, forKey: CodingKeys.uninstancedItemObjectives)
            uninstancedItemPerks = try? container.decode([Int: Destiny.Entities.Items.DestinyItemPerksComponent].self, forKey: CodingKeys.uninstancedItemPerks)
        }
    }
}
