// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyGuardianRankIconBackgroundsDefinition.swift

import Foundation

public extension Destiny.Definitions.GuardianRanks {
    struct DestinyGuardianRankIconBackgroundsDefinition: Codable {
        public var backgroundEmptyBlueGradientBorderedImagePath: String?

        public var backgroundEmptyBorderedImagePath: String?

        public var backgroundFilledBlueBorderedImagePath: String?

        public var backgroundFilledBlueGradientBorderedImagePath: String?

        public var backgroundFilledBlueLowAlphaImagePath: String?

        public var backgroundFilledBlueMediumAlphaImagePath: String?

        public var backgroundFilledGrayHeavyAlphaBorderedImagePath: String?

        public var backgroundFilledGrayMediumAlphaBorderedImagePath: String?

        public var backgroundFilledWhiteImagePath: String?

        public var backgroundFilledWhiteMediumAlphaImagePath: String?

        public var backgroundPlateBlackAlphaImagePath: String?

        public var backgroundPlateBlackImagePath: String?

        public var backgroundPlateWhiteImagePath: String?

        public enum CodingKeys: String, CodingKey {
            case backgroundEmptyBlueGradientBorderedImagePath
            case backgroundEmptyBorderedImagePath
            case backgroundFilledBlueBorderedImagePath
            case backgroundFilledBlueGradientBorderedImagePath
            case backgroundFilledBlueLowAlphaImagePath
            case backgroundFilledBlueMediumAlphaImagePath
            case backgroundFilledGrayHeavyAlphaBorderedImagePath
            case backgroundFilledGrayMediumAlphaBorderedImagePath
            case backgroundFilledWhiteImagePath
            case backgroundFilledWhiteMediumAlphaImagePath
            case backgroundPlateBlackAlphaImagePath
            case backgroundPlateBlackImagePath
            case backgroundPlateWhiteImagePath
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            backgroundEmptyBlueGradientBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundEmptyBlueGradientBorderedImagePath)
            backgroundEmptyBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundEmptyBorderedImagePath)
            backgroundFilledBlueBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledBlueBorderedImagePath)
            backgroundFilledBlueGradientBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledBlueGradientBorderedImagePath)
            backgroundFilledBlueLowAlphaImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledBlueLowAlphaImagePath)
            backgroundFilledBlueMediumAlphaImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledBlueMediumAlphaImagePath)
            backgroundFilledGrayHeavyAlphaBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledGrayHeavyAlphaBorderedImagePath)
            backgroundFilledGrayMediumAlphaBorderedImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledGrayMediumAlphaBorderedImagePath)
            backgroundFilledWhiteImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledWhiteImagePath)
            backgroundFilledWhiteMediumAlphaImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundFilledWhiteMediumAlphaImagePath)
            backgroundPlateBlackAlphaImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundPlateBlackAlphaImagePath)
            backgroundPlateBlackImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundPlateBlackImagePath)
            backgroundPlateWhiteImagePath = try? container.decode(String.self, forKey: CodingKeys.backgroundPlateWhiteImagePath)
        }
    }
}
