// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyPresentationChildBlock.swift

import Foundation

public extension Destiny.Definitions.Presentation {
    struct DestinyPresentationChildBlock: Codable {
        public var displayStyle: Destiny.DestinyPresentationDisplayStyle?

        public var parentPresentationNodeHashes: [UInt32]?

        public var presentationNodeType: Destiny.DestinyPresentationNodeType?

        public enum CodingKeys: String, CodingKey {
            case displayStyle
            case parentPresentationNodeHashes
            case presentationNodeType
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            displayStyle = try? container.decode(Destiny.DestinyPresentationDisplayStyle.self, forKey: CodingKeys.displayStyle)
            parentPresentationNodeHashes = try? container.decode([UInt32].self, forKey: CodingKeys.parentPresentationNodeHashes)
            presentationNodeType = try? container.decode(Destiny.DestinyPresentationNodeType.self, forKey: CodingKeys.presentationNodeType)
        }
    }
}
