// This File was auto generated by BungoKitGen
//
// File: DestinyScoredPresentationNodeBaseDefinition.swift

import Foundation

public extension Destiny.Definitions.Presentation {
    struct DestinyScoredPresentationNodeBaseDefinition: Codable {
        /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
        /// When entities refer to each other in Destiny content, it is this hash that they are referring to.
        public var hash: UInt32?
        /// The index of the entity as it was found in the investment tables.
        public var index: Int32?
        public var maxCategoryRecordScore: Int32?
        /// A quick reference to presentation nodes that have this node as a child. Presentation nodes can be parented under multiple parents.
        public var parentNodeHashes: [UInt32]?
        public var presentationNodeType: Destiny.DestinyPresentationNodeType?
        /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
        public var redacted: Bool?
        public var traitHashes: [UInt32]?
        public var traitIds: [String]?

        public enum CodingKeys: String, CodingKey {
            case hash
            case index
            case maxCategoryRecordScore
            case parentNodeHashes
            case presentationNodeType
            case redacted
            case traitHashes
            case traitIds
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            hash = try? container.decode(UInt32.self, forKey: CodingKeys.hash)
            index = try? container.decode(Int32.self, forKey: CodingKeys.index)
            maxCategoryRecordScore = try? container.decode(Int32.self, forKey: CodingKeys.maxCategoryRecordScore)
            parentNodeHashes = try? container.decode([UInt32].self, forKey: CodingKeys.parentNodeHashes)
            presentationNodeType = try? container.decode(Destiny.DestinyPresentationNodeType.self, forKey: CodingKeys.presentationNodeType)
            redacted = try? container.decode(Bool.self, forKey: CodingKeys.redacted)
            traitHashes = try? container.decode([UInt32].self, forKey: CodingKeys.traitHashes)
            traitIds = try? container.decode([String].self, forKey: CodingKeys.traitIds)
        }
    }
}
