// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: GetClanFireteam.swift

import Foundation

public extension Requests.Fireteam {
    /// Gets a specific fireteam.
    struct GetClanFireteamRequest: BungoRequest {
        public typealias Response = Fireteam.FireteamResponse

        public struct Parameters: BungoRequestParameters {
            public var query: [String: String]
            public var path: [String: String]

            public init(fireteamId: Int64, groupId: Int64) {
                query = [:]
                path = [:]

                path["fireteamId"] = "\(fireteamId)"
                path["groupId"] = "\(groupId)"
            }
        }

        public let path = "/Fireteam/Clan/{groupId}/Summary/{fireteamId}/"
        public let parameters: Parameters
        public let method: HTTPMethod = .get
        public let successStatus: Int = 200

        public init(parameters: Parameters) {
            self.parameters = parameters
        }
    }
}
