// This File was auto generated by BungoCodeGen and should not be modified.
//
// File: DestinyItemPlugDefinition.swift

import Foundation

public extension Destiny.Definitions.Items {
    /// If an item is a Plug, its DestinyInventoryItemDefinition.plug property will be populated with an instance of one of these bad boys.
    /// This gives information about when it can be inserted, what the plug's category is (and thus whether it is compatible with a socket... see DestinySocketTypeDefinition for information about Plug Categories and socket compatibility), whether it is enabled and other Plug info.
    struct DestinyItemPlugDefinition: Codable {
        /// The alternate plug of the plug: only applies when the item is in states that only the server can know about and control, unfortunately. See AlternateUiPlugLabel for the related label info.
        public var alternatePlugStyle: Destiny.PlugUiStyles?

        /// If the plug meets certain state requirements, it may have an alternative label applied to it. This is the alternative label that will be applied in such a situation.
        public var alternateUiPlugLabel: String?

        /// It's not enough for the plug to be inserted. It has to be enabled as well. For it to be enabled, it may require materials. This is the hash identifier for the DestinyMaterialRequirementSetDefinition for those requirements, if there is one.
        public var enabledMaterialRequirementHash: UInt32?

        /// The rules around whether the plug, once inserted, is enabled and providing its benefits.
        /// The live data DestinyItemPlugComponent.enableFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
        public var enabledRules: [Destiny.Definitions.Items.DestinyPlugRuleDefinition]?

        /// IF not null, this plug provides Energy capacity to the item in which it is socketed. In Armor 2.0 for example, is implemented in a similar way to Masterworks, where visually it's a single area of the UI being clicked on to "Upgrade" to higher energy levels, but it's actually socketing new plugs.
        public var energyCapacity: Destiny.Definitions.Items.DestinyEnergyCapacityEntry?

        /// IF not null, this plug has an energy cost. This contains the details of that cost.
        public var energyCost: Destiny.Definitions.Items.DestinyEnergyCostEntry?

        /// If inserting this plug requires materials, this is the hash identifier for looking up the DestinyMaterialRequirementSetDefinition for those requirements.
        public var insertionMaterialRequirementHash: UInt32?

        /// The rules around when this plug can be inserted into a socket, aside from the socket's individual restrictions.
        /// The live data DestinyItemPlugComponent.insertFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
        public var insertionRules: [Destiny.Definitions.Items.DestinyPlugRuleDefinition]?

        /// If TRUE, this plug is used for UI display purposes only, and doesn't have any interesting effects of its own.
        public var isDummyPlug: Bool?

        /// If you successfully socket the item, this will determine whether or not you get "refunded" on the plug.
        public var onActionRecreateSelf: Bool?

        /// Do you ever get the feeling that a system has become so overburdened by edge cases that it probably should have become some other system entirely? So do I!
        /// In totally unrelated news, Plugs can now override properties of their parent items. This is some of the relevant definition data for those overrides.
        /// If this is populated, it will have the override data to be applied when this plug is applied to an item.
        public var parentItemOverride: Destiny.Definitions.Items.DestinyParentItemOverride?

        /// Indicates the rules about when this plug can be used. See the PlugAvailabilityMode enumeration for more information!
        public var plugAvailability: Destiny.PlugAvailabilityMode?

        /// The hash for the plugCategoryIdentifier. You can use this instead if you wish: I put both in the definition for debugging purposes.
        public var plugCategoryHash: UInt32?

        /// The string identifier for the plug's category. Use the socket's DestinySocketTypeDefinition.plugWhitelist to determine whether this plug can be inserted into the socket.
        public var plugCategoryIdentifier: String?

        public var plugStyle: Destiny.PlugUiStyles?

        /// In the game, if you're inspecting a plug item directly, this will be the item shown with the plug attached. Look up the DestinyInventoryItemDefinition for this hash for the item.
        public var previewItemOverrideHash: UInt32?

        /// Plugs can have arbitrary, UI-defined identifiers that the UI designers use to determine the style applied to plugs. Unfortunately, we have neither a definitive list of these labels nor advance warning of when new labels might be applied or how that relates to how they get rendered. If you want to, you can refer to known labels to change your own styles: but know that new ones can be created arbitrarily, and we have no way of associating the labels with any specific UI style guidance... you'll have to piece that together on your end. Or do what we do, and just show plugs more generically, without specialized styles.
        public var uiPlugLabel: String?

        public enum CodingKeys: String, CodingKey {
            case alternatePlugStyle
            case alternateUiPlugLabel
            case enabledMaterialRequirementHash
            case enabledRules
            case energyCapacity
            case energyCost
            case insertionMaterialRequirementHash
            case insertionRules
            case isDummyPlug
            case onActionRecreateSelf
            case parentItemOverride
            case plugAvailability
            case plugCategoryHash
            case plugCategoryIdentifier
            case plugStyle
            case previewItemOverrideHash
            case uiPlugLabel
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            alternatePlugStyle = try? container.decode(Destiny.PlugUiStyles.self, forKey: CodingKeys.alternatePlugStyle)
            alternateUiPlugLabel = try? container.decode(String.self, forKey: CodingKeys.alternateUiPlugLabel)
            enabledMaterialRequirementHash = try? container.decode(UInt32.self, forKey: CodingKeys.enabledMaterialRequirementHash)
            enabledRules = try? container.decode([Destiny.Definitions.Items.DestinyPlugRuleDefinition].self, forKey: CodingKeys.enabledRules)
            energyCapacity = try? container.decode(Destiny.Definitions.Items.DestinyEnergyCapacityEntry.self, forKey: CodingKeys.energyCapacity)
            energyCost = try? container.decode(Destiny.Definitions.Items.DestinyEnergyCostEntry.self, forKey: CodingKeys.energyCost)
            insertionMaterialRequirementHash = try? container.decode(UInt32.self, forKey: CodingKeys.insertionMaterialRequirementHash)
            insertionRules = try? container.decode([Destiny.Definitions.Items.DestinyPlugRuleDefinition].self, forKey: CodingKeys.insertionRules)
            isDummyPlug = try? container.decode(Bool.self, forKey: CodingKeys.isDummyPlug)
            onActionRecreateSelf = try? container.decode(Bool.self, forKey: CodingKeys.onActionRecreateSelf)
            parentItemOverride = try? container.decode(Destiny.Definitions.Items.DestinyParentItemOverride.self, forKey: CodingKeys.parentItemOverride)
            plugAvailability = try? container.decode(Destiny.PlugAvailabilityMode.self, forKey: CodingKeys.plugAvailability)
            plugCategoryHash = try? container.decode(UInt32.self, forKey: CodingKeys.plugCategoryHash)
            plugCategoryIdentifier = try? container.decode(String.self, forKey: CodingKeys.plugCategoryIdentifier)
            plugStyle = try? container.decode(Destiny.PlugUiStyles.self, forKey: CodingKeys.plugStyle)
            previewItemOverrideHash = try? container.decode(UInt32.self, forKey: CodingKeys.previewItemOverrideHash)
            uiPlugLabel = try? container.decode(String.self, forKey: CodingKeys.uiPlugLabel)
        }
    }
}
