// This File was auto generated by BungoKitGen
//
// File: DestinyParentItemOverride.swift

import Foundation

public extension Destiny.Definitions.Items {
    struct DestinyParentItemOverride: Codable {
        public var additionalEquipRequirementsDisplayStrings: [String]?
        public var pipIcon: String?

        public enum CodingKeys: String, CodingKey {
            case additionalEquipRequirementsDisplayStrings
            case pipIcon
        }

        public init(from decoder: Decoder) throws {
            let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)

            additionalEquipRequirementsDisplayStrings = try? container.decode([String].self, forKey: CodingKeys.additionalEquipRequirementsDisplayStrings)
            pipIcon = try? container.decode(String.self, forKey: CodingKeys.pipIcon)
        }
    }
}
